codeforamerica/il-gcc-form-flow

.github/workflows/deploy-to-staging.yaml

- https://www.aptible.com/docs/continuous-integration-provider-deployment

Use ssh step from aptible docs

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/gcc-icons.html
src/main/resources/templates/gcc/onboarding-getting-started.html
src/main/resources/templates/index.html

[#186713028](https://www.pivotaltracker.com/story/show/186713028)
This PR only adds the `onboarding-getting-started` screen.
- Define default color to all text to match designs
- Add icon from Figma
- Make eligibility table reusable on multiple pages (`index` and `onboarding-getting-started`)
- Add screen content

Add onboarding-getting-started

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/index.html

[#186713028](https://www.pivotaltracker.com/story/show/186713028)
- Paired with Carlie
- Update demo banner to use idhs colors
- Change estimated time to 20 minutes
- Make hero image more responsive

Add design updates to home page

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/static/assets/css/custom.css

[#186713028](https://www.pivotaltracker.com/story/show/186713028)
- Remove duplicate keys `onboarding-getting-started.title` and `onboarding-getting-started.header`
- Replace broken characters in `es`
- Add missing styles for home page hero image (to align with pairing with Carlie)

Fix index translations 186713028

---

src/main/resources/application-demo.yaml
src/main/resources/application.yaml
src/test/java/org/ilgcc/app/utils/Page.java

- Adding "demo" env for auto-deploying with main branch
- tweak to testing for checking for missing message properties

Infrastructure updates

---

intellij-settings/IlGccLiveTemplates.xml

Here's a [video](https://www.loom.com/share/046b8e1591cd4325922b90ca73611774?sid=ba85e1f5-14fa-486a-aeb9-8b6247dfbacf) showing how we use live templates. I added a new xml file for this project specific ones.

Add GCC specific live template file for us to share

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/gcc/activities-class-weekly-schedule.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[#186900934](https://www.pivotaltracker.com/story/show/186900934)
- new screen activities-class-weekly-schedule .

Activities class weekly schedule 186900934

---

package-lock.json
package.json
src/test/java/org/ilgcc/app/utils/Page.java

Set up [percy](https://percy.io/Code-for-America/snlab-il-ccap)

Set up Percy

---

src/main/java/org/ilgcc/app/submission/actions/SetLanguagePreferences.java
src/main/resources/templates/fragments/mixpanelTracking.html

Fixes for language preference tracking 
- track previous and selected languages
- track language change on language-preference page
- track component used to change language (element_id)

Language pref fixes

---

src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/index.html

#187042038
1. Match ggc-app's desktop and mobile appearances to the designs in figma.  
[ Figma ]( https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1727-19181&mode=design&t=83snes9SLqPUe6jZ-4 )

Update landing page

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/children-ccap-in-care.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

PT#23186822601
Adding ccap in care page

Adding ccap in care page

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/gcc/activities-ed-program-type.html

[#186900920](https://www.pivotaltracker.com/story/show/186900920)
- change screen to use a new implementation of radio.

Activities ed program type 186900920

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/children-ccap-info.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

PT#186822601
Adding children CCAP info page
[Figma link](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190-34110&mode=design&t=IijxqoooxMwgCGi4-0)

Adding CCAP info screen

---

.github/workflows/codeql.yaml

Adding code analysis config to run on PRs
Results (from main) will show up here https://github.com/codeforamerica/il-gcc-form-flow/security/code-scanning

Adding codeql workflow 🍖 

---

.github/workflows/run-percy.yaml

PT#186712950
Adding a Github action to run [percy](https://percy.io/Code-for-America/snlab-il-ccap)

Adding percy workflow

---

.github/pull_request_template.md
.github/workflows/run-percy.yaml
src/main/resources/templates/gcc/children-ccap-info.html

- Revert accidental removal of helpText
- Update PR template - we add testing instructions _after_ PR has been merged 
- Added weekly schedule for Percy run

various fixes

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/templates/gcc/children-ccap-info.html

Small typo to change `childIsUScitizen` to `childIsUsCitizen`

Fix camel case typo 🍖

---

.github/workflows/codeql.yaml
.github/workflows/deploy-to-staging.yaml
build.gradle
src/main/resources/application.yaml

PT#186712950
Adding configuration for Sentry integration
- set up project in sentry
- importing sentry dependencies
- updating deploy script to include sentry info
- updated env configs
In local `.env`
```diff
+ SENTRY_DSN=''
```

Adding Sentry config

---

build.gradle
src/main/resources/application.yaml

Removing unneeded config for Sentry - seems like it's getting picked up by just setting the env variable 🤷

Fix sentry config

---

app.json

Review app config

---

src/main/java/org/ilgcc/app/submission/actions/ValidateChildrenCCAPStartDate.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

Update error messages on update-childcare-screen

---

app.json

Fix review-apps

---

build.gradle
src/test/java/org/ilgcc/app/journeys/CcapStartDateTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/utils/AbstractMockMvcTest.java
src/test/java/org/ilgcc/app/utils/FormScreen.java
src/test/resources/application-test.yaml

Adding test classes from FFL and using for validation
- refactored ccapStartDate validation in `GccJourneyTest` into `CcapStartDateTest`
- Bump dependencies

MockMvc journey tests

---

.github/workflows/run-tests.yaml
build.gradle
src/main/resources/messages.properties
src/main/resources/templates/fragments/inputError.html
src/main/resources/templates/fragments/inputs/timeRange.html
src/test/java/org/ilgcc/app/journeys/AccessibilityJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/utils/AccessibilityPage.java

PT#186712950
Adding axe devtools unit tests to catch some accessibility violations

Adding axe tests

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties

Fix error messages and remove untranslated copy - these are getting copied into transifex as "translated"

Copy fixes

---

src/main/resources/templates/fragments/inputs/date.html

Overriding date component to correctly handle errors on the whole fieldset (cross field validation)
See https://github.com/codeforamerica/form-flow/pull/527

Overriding date component

---

app.json
build.gradle

Using properties instead of system to get env variable

Build config update to load local library

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/parent-partner-contact.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[#187108143](https://www.pivotaltracker.com/story/show/187108143)
Add the `parent-partner-contact` screen
[Figma screen](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190%3A34079&mode=design&t=dNEq86FDZVxntUOR-1)

Add parent-partner-contact screen

---

src/main/resources/templates/fragments/inputs/overrides/radio.html
src/main/resources/templates/gcc/parent-contact.html

override radio button

---

src/main/resources/static/assets/css/custom.css
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

- Re-enabling the download and verify PDF in journey test
- Reduced font size for demo banner on smaller screens

PDF Test fixes

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/conditions/ParentPartnerQualifies.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/inputs/yesNoRadios.html
src/main/resources/templates/gcc/parent-qualifying-partner.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

PT#186714054
- Adding "parent-qualifying-partner" page
- new fragment for yes/no radio buttons
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190-34091&mode=design&t=NF8VDVamdoWxjTZp-0)

Adding "parent-qualifying-partner" page

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/gcc/children-ccap-start-date.html

Renaming `title` message property for consistency

Renaming property for consistency

---

src/main/resources/messages.properties
src/main/resources/templates/fragments/inputs/overrides/yesOrNo.html
src/main/resources/templates/gcc/parent-partner-contact.html
src/main/resources/templates/gcc/parent-partner-info-disability.html

[#187108143](https://www.pivotaltracker.com/story/show/187108143)
Address [these comments](https://www.pivotaltracker.com/story/show/187108143/comments/240606528).
- Fix labels
- Add ids to buttons
- I updated to latest Google Java styles from library, hence why spacing is now 4 spaces

Fix labels and add ids to buttons for parent partner screens

---

.github/reviewer-lottery.yml
.github/workflows/auto-assignee.yaml

Updated auto-assign workflow to also randomly assign a reviewer when the pull request is ready for review

Adding "reviewer lottery" to github action

---

build.gradle
src/main/resources/templates/gcc/children-ccap-info.html
src/main/resources/templates/gcc/parent-info-basic-2.html

Follow-up of Race/Ethnicity field in #39 and #90 
[See comment](https://www.pivotaltracker.com/story/show/186713761/comments/240454405)
- Update options for race/ethnicity inputs only

Add "no answer" field for race/ethnicity

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/gcc-icons.html
src/main/resources/templates/gcc/parent-intro-family-info.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[#186901269](https://www.pivotaltracker.com/story/show/186901269)
Created `parent-intro-family-info` screen based on design 
Added Journey test to verify that we reach the page 
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190-41219&mode=design&t=C247vjybqCwRy8di-4)

Parent intro family info

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/actions/ValidateAdultDependentBirthdate.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/children-info-basic.html
src/main/resources/templates/gcc/parent-add-adults-detail.html
src/main/resources/templates/gcc/parent-add-adults.html
src/main/resources/templates/gcc/parent-partner-info-basic.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

PT#186901269
Adding initial version of "parent-add-adults" page when no adults have been added
Follow-up
- Implement subflow
- Set `number_of_adults` for tracking
[Figma link](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1289-13955&mode=design&t=iWKag0lNjgyL8vGi-0)

Adding "parent-add-adults" page - no adults added

---

src/main/java/org/ilgcc/app/submission/actions/ValidateAdultDependentBirthdate.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/messages.properties
src/main/resources/templates/fragments/mixpanelTracking.html
src/main/resources/templates/gcc/children-info-basic.html
src/main/resources/templates/gcc/delete-person.html
src/main/resources/templates/gcc/parent-add-adults.html
src/main/resources/templates/gcc/parent-partner-info-basic.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

PT#186901269
- Added "delete person" functionality
- Updated mixpanel tracking
- Other cleanup and consolidation
Follow-up
- Didn't overwrite the date of birth help text - might need some a11y discussion
[Figma link](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=2889-10142&mode=design&t=if63ovfkJX8QPaMn-0)

Adding "delete-parent" screen and tracking

---

.github/workflows/run-tests.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-ed-program-name.html
src/main/resources/templates/gcc/activities-ed-program-type.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/utils/AccessibilityPage.java

Add the deque best practice rule set to our a11y tests.
- https://dequeuniversity.com/rules/axe/4.8/#best-practices-rules

Add deque best practices to our ruleset 🍖

---

src/main/resources/templates/gcc/parent-add-adults.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

PT#186901269
- Updating link ids to be more descriptive for tracking purposes
- Other - test update to check which elements don't match before checking overall elements

More descriptive element-links

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/utils/ChildcareReasonOption.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-parent-type.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

#187262348
[#187262348](https://www.pivotaltracker.com/story/show/187262348)
* Updated `activities-parent-type` screen
* Updated `message-properties` and added a new `InputOption` class
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=3167-9169&mode=design&t=MlCEeeHiz3awLgsO-4)

Activities-parent-type.html Screen

---

.github/reviewer-lottery.yml

temp leaving out CB from code-review - will uncomment later

temp leaving out CB from code-review

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[187270719](https://www.pivotaltracker.com/story/show/187270719)
Reporting class schedule on a weekend results in an error
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=748-12965&mode=design&t=9ShMc3UtmvRx1RDm-0)
- [ X ] Added relevant tests
- [ X ] Meets acceptance criteria

fix bug scheduleOnWeekend

---

src/main/resources/application.yaml
src/test/resources/application-test.yaml

Generating pdfs as un-flattened so that the fields can be tabbed through

Generating pdfs as un-flattened

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/gcc/activities-ed-program-info.html
src/main/resources/templates/gcc/activities-ed-program-name.html
src/main/resources/templates/gcc/activities-ed-program-type.html
src/main/resources/templates/gcc/activities-employer-address.html

- removed some duplicates
- rearranged
- updated some error messages
I'm working on #195 and noticed some opportunities for cleanup

clean-up message properties

---

.github/reviewer-lottery.yml

Add new teammates to review lottery.

Add new teammates to review lottery

---

src/main/resources/messages.properties

https://codeforamerica.atlassian.net/browse/CCAP-40
Update message.properties to change child age limit from 21 to 18
https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190-34122&mode=design&t=Jlbd6CQd9V3Uqsf3-4
- [N/A] Added relevant tests

Change child age limit to 18

---

.github/reviewer-lottery.yml

Allow @analoo to be picked for review with a pull request is ready for review.

Add Ana to review lottery

---

build.gradle
src/main/resources/messages.properties
src/main/resources/templates/gcc/parent-comm-preference.html
src/main/resources/templates/gcc/parent-no-permanent-address.html
src/test/java/org/ilgcc/app/journeys/OptInJourneyTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

…mm-preference.html screen
Added OptInJourneyTest.java
[Jira Ticket](https://codeforamerica.atlassian.net/browse/CCAP-28?atlOrigin=eyJpIjoiM2JiNzE2NDhjMGY2NGJiYjhlNTM5OTk5Njg2OGZkM2MiLCJwIjoiaiJ9)
A bug was found when we changed our client flow for email opt-in.  We went from one screen to two new screens.  Our code for clients experiencing homeless contained a link to the original single screen.   We changed this arrangement and added logic for additional considerations to this ticket.

CCAP-28-bug-fix

---

src/main/resources/flows-config.yaml

[Jira](https://codeforamerica.atlassian.net/browse/CCAP-35?atlOrigin=eyJpIjoiZjgwOGNkN2QwZjU4NDI0ZWJjNThmOGY1YWZjN2E0NGQiLCJwIjoiaiJ9)
Updates `Yes, submit and finish` button to link to `submit-next-steps` screen

Updated flows-config.yaml to match jira

---

src/test/java/org/ilgcc/app/pdf/ApplicantEducationSchedulePreparerTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

CCAP-39 | Map Primary Parent Education -  class schedule

---

.github/reviewer-lottery.yml

Remove Shawn and tentatively add Marc

Change reviewers

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-partner-employer-name.html

CCAP-25
Update activities-partner-employer-name copy to match figma.  
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?node-id=1322-7792&t=y5u0LwKgTY7D993C-4)

CCAP 25 copy change to employer name screen

---

.github/workflows/deploy-to-prod.yaml
.github/workflows/deploy-to-staging.yaml
sample.env
src/main/resources/application-production.yaml
src/main/resources/application.yaml
src/main/resources/templates/fragments/toolbar.html

[CCAP-155](https://codeforamerica.atlassian.net/browse/CCAP-155)
- Add deploy to prod action
- Add demo banner for prod
Please add this line to your local `.env` file:
```
AWS_BUCKET=get-child-care-illinois-dev
```
[CCAP-155]: https://codeforamerica.atlassian.net/browse/CCAP-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add deploy to production

---

.github/workflows/deploy-to-prod.yaml
.github/workflows/deploy-to-staging.yaml

[CCAP-155](https://codeforamerica.atlassian.net/browse/CCAP-155)
[CCAP-155]: https://codeforamerica.atlassian.net/browse/CCAP-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the ssh private key name

---

.github/workflows/deploy-to-staging.yaml
src/main/resources/application-demo.yaml
src/main/resources/application-production.yaml
src/main/resources/application-staging.yaml

Remove staging overlap of s3 bucket name

---

.github/workflows/codeql.yaml

Update codeql action to stop running tests

---

.github/workflows/deploy-to-prod.yaml

Remove git push command from deploy to prod action

---

.github/workflows/deploy-to-prod.yaml

Aptible deploy to prod configuration changes

---

.github/workflows/deploy-to-prod.yaml

Go all in on the new way of doing an Aptible deploy.

Remove old way of doing the prod deploy

---

src/main/resources/templates/index.html

Address accessibility issues

---

.github/workflows/deploy-to-prod.yaml
src/main/resources/application-production.yaml

- Change db reference in the prod yaml

Deploy with all secrets

---

.github/workflows/deploy-to-prod.yaml
sample.env
src/main/resources/application.yaml
src/main/resources/templates/fragments/toolbar.html
src/test/resources/application-test.yaml

- Add it to the sample env
- Use refs for sentry release version

Make the AWS region a configuration variable

---

src/main/resources/messages.properties

https://codeforamerica.atlassian.net/browse/CCAP-119
Updated 7 strings, per the ticket.
https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190-34110&mode=design&t=aawIdv53KuxkQfVb-4
(^^ linked from original Jira ticket)

[CCAP-119] Policy feedback copy changes -- updating 7 strings

---

src/main/resources/messages_es.properties

https://codeforamerica.atlassian.net/browse/CCAP-233
Somehow the spanish translation file's encoding got changed

CCAP-233: Fixing document encoding for spanish translations

---

README.md

This work was done as part of my setting up the local development environment and does not exist as a Jira ticket.
Updates the README setup information to be more inline with the actual setup process based on my own experience setting up the project for local development.

Update README setup instructions

---

sample.env
src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/application.yaml
src/test/resources/application-test.yaml

[CCAP-61](https://codeforamerica.atlassian.net/browse/CCAP-61)
* Encrypt `parentSsn` and `parentPartnerSSN`
* Add `ENCRYPTION_KEY` env variable (has been added to `staging`, `demo`, and `production` environments already)
To get the encryption to work locally:
* Add `ENCRYPTION_KEY` to your `.env`
* The value can be found in LastPass in `SNLab IL GitHub Secrets`
* With the key set in your `.env` when running the app locally, go through the form and fill out a SSN
* Look at the local database and you should see that the value is encrypted and you can't see it's actual value in the database
[CCAP-61]: https://codeforamerica.atlassian.net/browse/CCAP-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ccap-61 encrypt fields

---

Dockerfile

removing port

---

Dockerfile
src/main/resources/application-staging.yaml

Trying to expose the dashboard in staging

---

src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
src/test/java/org/ilgcc/app/journeys/DesignSystemCfaUswdsJourneyTest.java
src/test/java/org/ilgcc/app/journeys/DesignSystemHoneycrispJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/OptInJourneyTest.java
src/test/java/org/ilgcc/app/journeys/ParentBirthJourneyTest.java
src/test/java/org/ilgcc/app/journeys/SignatureJourneyTest.java
src/test/java/org/ilgcc/app/journeys/StaticPagesJourneyTest.java
src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
src/test/java/org/ilgcc/app/utils/Page.java

[Link](https://codeforamerica.atlassian.net/browse/CCAP-249)
- Create a method to return message string in english
- Update tests

Add messageSource in Tests

---

Dockerfile
src/main/resources/application-staging.yaml

Disabling the dashboard in staging

---

src/main/resources/messages_es.properties

fixing spanish encoding

---

src/main/java/org/ilgcc/app/utils/PreparerUtilities.java

https://codeforamerica.atlassian.net/browse/CCAP-253
Github's scan found a missing try/catch around a possible NumberFormatException

[CCAP-253]: Handling a NumberFormatException to appease Github

---

Procfile

setting up a new dashboard container

---

Dockerfile
Procfile

Removing EXPOSE 8000 from Dockerfile 

---

Dockerfile
Procfile

assigning port 8000 to dashboard

---

Dockerfile
Procfile

removing port 8000 from dashboard config

---

Dockerfile

Switching ENTRYPOINT to CMD

---

Dockerfile

Exposing port 8000 again

---

Dockerfile

Switching to Jammy

---

Dockerfile
Procfile
src/main/resources/application.yaml

Enabling dashboard universally

---

.github/workflows/deploy-to-staging.yaml

[CCAP-231](https://codeforamerica.atlassian.net/browse/CCAP-231)
- Refactor staging release to use the same method as production
- We had an issue in the previous staging that would deploy to Aptible _twice_. Doubling the time it takes. This refactor halves the time this action runs.
[CCAP-231]: https://codeforamerica.atlassian.net/browse/CCAP-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor staging GitHub deploy action

---

Procfile
src/main/resources/application.yaml

Trying to disable dashboard staging

---

Procfile
src/main/resources/application.yaml

Re-enabling jobrunr dash universally

---

Procfile

Trying to find the script in the correct place for aptible

---

Procfile

Reversing the script attempts at getting Aptible to work

---

Procfile
scripts/jobrunr_dashboard_launcher.sh

Alpine doesn't/didn't support bash in the past

---

src/main/resources/application.yaml

Disabling jobrunr dashboard for main webapp

---

Procfile

Removing unused JAVA_OPTS

---

Procfile

Reverting removing unused JAVA_OPTS

---

Procfile
scripts/webapp_launcher.sh

We are seeing errors in the aptible logs where JAVA_OPTS can not be found. Hoping this solves it.

moving web launcher to a script, to try to fix JAVA_OPTS error

---

src/main/java/org/ilgcc/app/inputs/Gcc.java

[Link to Jira](https://codeforamerica.atlassian.net/browse/CCAP-245)
- Require partnerCompanyName
- Confirm that journey test adds partnerCompany Name

Ccap 245 require employer name for partner jobs

---

src/main/java/org/ilgcc/app/pdf/ParentPartnerPreparer.java
src/main/java/org/ilgcc/app/pdf/ParentPreparer.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/test/java/org/ilgcc/app/pdf/ParentPartnerPreparerTest.java
src/test/java/org/ilgcc/app/pdf/ParentPreparerTest.java

[Link](https://codeforamerica.atlassian.net/browse/CCAP-241)
- Create method that takes the date key and returns a string that either shows a full date or a partial date when day is not included ✅ 
- Add unit test to show that a date without a day will be properly set to : "DD/YYYY" ✅ 
- Check that there is a validation that allows the user to submit no values, a full date, or a date with a day missing ✅

Add date to PDF for school programs only day is missing

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/onboarding-getting-started.html
src/main/resources/templates/index.html

Improve english strings per spanish session

---

src/main/java/org/ilgcc/app/utils/LanguageOption.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/fragments/inputs/selectOption.html
src/main/resources/templates/gcc/onboarding-language-pref.html

[CCAP-71](https://codeforamerica.atlassian.net/browse/CCAP-71)
Add more language options on the language preference screen.
[CCAP-71]: https://codeforamerica.atlassian.net/browse/CCAP-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-71 Add more language options

---

src/main/resources/templates/gcc/parent-info-review.html

[CCAP-270](https://codeforamerica.atlassian.net/browse/CCAP-270)
- Change parent contact info from `parent-contact` to `parent-contact-info`
- Using `||` format for consistency
[CCAP-270]: https://codeforamerica.atlassian.net/browse/CCAP-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-270 Fix contact info link

---

build.gradle
src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/messages.properties
src/main/resources/templates/gcc/children-info-basic.html
src/main/resources/templates/gcc/parent-info-basic-1.html
src/main/resources/templates/gcc/parent-partner-info-basic.html
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java

[CCAP-70](https://codeforamerica.atlassian.net/browse/CCAP-70)
- Upgrade to version of FFL (1.3.7) that has the required upgrade
- In this document: [Here](https://docs.google.com/spreadsheets/d/1X5TlBFpIbxkTbDzrCfqNv8bhCqM3tnllo1NFVqITHxo/edit?gid=187665420#gid=187665420)
- Note which fields are required
- Note the asterisks that have been removed (To be removed in transifex on the english strings are merged)
- Note which fields have the required value
- Reorganized the input page to be organized by screen and screen order
[CCAP-70]: https://codeforamerica.atlassian.net/browse/CCAP-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade FFL to indicate required inputs

---

src/main/resources/messages.properties

Small change in english based on translation chat

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-ed-program-info.html
src/main/resources/templates/gcc/activities-employer-address.html
src/main/resources/templates/gcc/activities-partner-ed-program-info.html
src/main/resources/templates/gcc/activities-partner-employer-address.html

[Part of supporting Spanish Translations](https://codeforamerica.atlassian.net/browse/CCAP-287)

Update English text strings based on spanish translation session 4

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-add-ed-program.html
src/main/resources/templates/gcc/activities-self-employment.html
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java

Fixes education screen 

---

src/main/resources/messages.properties

[CCAP-267] Missed a period

---

src/main/resources/templates/gcc/unearned-income-programs.html

Removes required tag on unearned income

---

src/main/java/org/ilgcc/app/inputs/Gcc.java

[Link](https://codeforamerica.atlassian.net/browse/CCAP-263)
- Just needed a validation for parent ssn

Add validation for parent partner ssn

---

src/main/resources/application.yaml

Add [metric export to datadog](https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.export)

Add datadog api key

---

build.gradle
src/main/java/org/ilgcc/app/config/DocumentTransferConfiguration.java
src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/java/org/ilgcc/jobs/PdfTransmissionJobService.java
src/main/resources/application-dev.yaml
src/main/resources/application-production.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3Test.java
src/test/java/org/ilgcc/jobs/SampleJobsTest.java
src/test/resources/application-test.yaml

[CCAP-206
](https://codeforamerica.atlassian.net/browse/CCAP-206?atlOrigin=eyJpIjoiZDhjMzM2NGU1ODQzNDc3MmFkMGUyZGFmMDNiODM2ODAiLCJwIjoiaiJ9)
Creates a jobrunr job for sending the generated PDF via the document transfer service.

CCAP-206 Setup Job Processor to send request to the Document Transfer Microservice

---

src/main/resources/templates/gcc/parent-contact-info.html

[Link](https://codeforamerica.atlassian.net/browse/CCAP-296)
Added conditional logic to show parent email required when it is required.

Conditionally add parent contact when required

---

src/main/java/org/ilgcc/app/config/ActuatorHttpExchangesConfiguration.java
src/main/resources/templates/fragments/head.html

https://codeforamerica.atlassian.net/browse/CCAP-307
Setting up Datadog RUM for IL GCC. Three new keys in Lastpass if you want to enable this for dev, otherwise it will work in Staging and Production.

[CCAP-307] Setting up Datadog RUM for IL GCC

---

src/main/resources/application-dev.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml

[CCAP-311] Disabling Smarty

---

src/main/resources/application.yaml

[CCAP-312] Re-enabling Smarty

---

src/main/java/org/ilgcc/app/pdf/NeedChildcareForChildren.java

https://codeforamerica.atlassian.net/browse/CCAP-316
Child relationship was missing the iteration, so the earlier children would lose their relationships in the mapping

[CCAP-316] Need to map child relationship by iteration

---

src/main/resources/application.yaml

https://codeforamerica.atlassian.net/browse/CCAP-293

[CCAP-293] Making pdf read-only

---

src/main/java/org/ilgcc/app/submission/actions/FormatParentConfirmationAddress.java
src/main/java/org/ilgcc/jobs/SampleJobProcessor.java

https://codeforamerica.atlassian.net/browse/CCAP-320
Just cleaning up some Datadog errors, and also removing an unused method from sample code

[CCAP-320] Handling null fields nicer

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/parent-info-intro.html

[Small Fry Ticket](https://codeforamerica.atlassian.net/browse/CCAP-126)
- Update copy

Update copy for parent-info-intro

---

.github/reviewer-lottery.yml

Remove Rapi, Uncomment Marc, Add Alex

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/children-childcare-hourly-schedule.html
src/main/resources/templates/gcc/children-childcare-weekly-schedule.html

Add future tense of child care questions when child is not in care

---

src/main/resources/messages.properties
src/main/resources/templates/index.html

https://codeforamerica.atlassian.net/browse/CCAP-306
Update to the text string for the home page. Easy peasy.
https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?node-id=6926-18940&t=nnGPg17c4LbE3RyO-0

[CCAP-306] Update pilot notice on landing page

---

src/main/resources/messages.properties

Adding final submission state text, so it gets translated and overrides the only English version from FFL
https://codeforamerica.atlassian.net/browse/CCAP-303

[CCAP-303] Adding final submission state text, so it gets translated and overrides the only English version from FFL

---

src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/faq.html

CCAP-305
Update FAQ page to match [FAQ Page Copy](https://docs.google.com/document/d/1Sb2Mqn_KE4Cc9GhFv3Bj9z-O-w1OKgIL/edit#heading=h.1fob9te)
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?node-id=5859-9839&t=KfMGw96h4TDJTavJ-4)

CCAP-305 Update FAQ page

---

src/main/resources/messages.properties

Add strings for translations

---

src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/head.html
src/main/resources/templates/fragments/toolbar.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/ParentBirthJourneyTest.java

[CCAP-69](https://codeforamerica.atlassian.net/browse/CCAP-69)
- If an error message is present, change the `title` and show a notice at the top of the screen
- Make sure title changes in tests
- Make sure the notice appears in tests
[Figma designs](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=3441-15714&mode=design&t=fBPL3w6C7FZxN0U7-4)
[CCAP-69]: https://codeforamerica.atlassian.net/browse/CCAP-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-69 Show error announcement minimum version

---

src/main/java/org/ilgcc/app/pdf/ApplicantEducationSchedulePreparer.java
src/main/java/org/ilgcc/app/pdf/ApplicantJobSchedulePreparer.java
src/main/java/org/ilgcc/app/pdf/ParentPartnerJobSchedulePreparer.java
src/main/java/org/ilgcc/app/pdf/PartnerEducationSchedulePreparer.java
src/main/java/org/ilgcc/app/submission/actions/ValidateActivitiesClassHourlySchedule.java
src/main/java/org/ilgcc/app/submission/actions/ValidateActivitiesJobSchedule.java
src/main/java/org/ilgcc/app/submission/actions/ValidateChildcareHourlySchedule.java
src/main/java/org/ilgcc/app/submission/actions/ValidateHourlySchedule.java
src/main/java/org/ilgcc/app/submission/actions/ValidatePartnerClassHourlySchedule.java
src/main/java/org/ilgcc/app/utils/AmPmSelectOption.java
src/main/java/org/ilgcc/app/utils/HourSelectOption.java
src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
src/main/resources/templates/fragments/inputs/timeRange.html
src/main/resources/templates/fragments/inputs/timeSelect.html
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/HourlyScheduleJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ApplicantEducationSchedulePreparerTest.java
src/test/java/org/ilgcc/app/pdf/ApplicantJobSchedulePreparerTest.java
src/test/java/org/ilgcc/app/pdf/ChildcareSchedulePreparerTest.java
src/test/java/org/ilgcc/app/pdf/ParentPartnerJobSchedulePreparerTest.java
src/test/java/org/ilgcc/app/pdf/PartnerEducationSchedulePreparerTest.java
src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
src/test/java/org/ilgcc/app/utils/TimeOption.java

[Link](https://codeforamerica.atlassian.net/browse/CCAP-340)
- Updates styling for all pages in CCAP-49. 
- Styling was off

[CCAP-340] - fix styling on ccap 49

---

src/main/resources/messages.properties

Update copy on children-add screen

---

src/main/resources/messages.properties

Basic string changes

---

src/main/java/org/ilgcc/app/utils/ChildCareProvider.java

https://codeforamerica.atlassian.net/browse/CCAP-365

[CCAP-365] Add additional providers to CCAP application

---

src/main/resources/templates/fragments/head.html

https://codeforamerica.atlassian.net/browse/CCAP-363?atlOrigin=eyJpIjoiZjAyODRjMmRjYWE5NDNlMWE2OGM3ZjUzY2IzMmU4OTIiLCJwIjoiaiJ9
Adds OG tags to head.html template

Add OG tags to header

---

build.gradle
src/main/resources/application-demo.yaml
src/main/resources/application-dev.yaml
src/main/resources/application-staging.yaml

https://codeforamerica.atlassian.net/browse/CCAP-341
Just updating the FFL version to use the confirmation number, and setting

[CCAP-341] Updating app to use new confirmation code

---

src/main/resources/templates/fragments/gcc-icons.html

[CCAP-381](https://codeforamerica.atlassian.net/browse/CCAP-381)
- Add `aria-hidden` to all GCC icons
[CCAP-381]: https://codeforamerica.atlassian.net/browse/CCAP-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-381 Add aria-hidden to all gcc-icons

---

src/main/resources/templates/fragments/inputs/timeSelect.html
src/main/resources/templates/fragments/screens/activities-ed-program-info.html
src/main/resources/templates/gcc/activities-employer-address.html
src/main/resources/templates/gcc/activities-partner-employer-address.html
src/test/java/org/ilgcc/app/journeys/HourlyScheduleJourneyTest.java

Updates remaining fields from Carl's comment in the ticket.
https://codeforamerica.atlassian.net/browse/CCAP-265?focusedCommentId=11903

Update remaining numeric fields

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties

[CCAP-378](https://codeforamerica.atlassian.net/browse/CCAP-378)
- Add McHenry County
- Change the copy on the landing page to include a hyperlink to the FAQ page and a reference to 7 centers.
[FAQ Screen](https://docs.google.com/document/d/1vwtwI1-GcqrGDGf3l1UEk161ahoGqVlCAX0BhmoYnlY/edit)
[Index Screen](https://docs.google.com/document/d/1vwtwI1-GcqrGDGf3l1UEk161ahoGqVlCAX0BhmoYnlY/edit)
[CCAP-378]: https://codeforamerica.atlassian.net/browse/CCAP-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-378] - Updates faq and banner to account for new counties and providers.

---

src/main/resources/messages.properties

Fixing an extra period

---

.github/reviewer-lottery.yml

Removes Cypress from reviewer lottery

---

src/main/java/org/ilgcc/app/submission/actions/ValidateHourlySchedule.java

Update validation logic to display minute errors when those exist

---

src/main/java/org/ilgcc/app/submission/actions/CheckClientSubmissionForProvider.java

Fixing broken enum loading

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties

https://codeforamerica.atlassian.net/browse/CCAP-294

[CCAP-294] Copy on submit-next-steps screen should match designs

---

src/main/java/org/ilgcc/app/ProviderLinkController.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/java/org/ilgcc/app/utils/TextUtilities.java
src/main/resources/templates/gcc/contact-provider-message.html
src/test/java/org/ilgcc/app/journeys/ProviderResponseShortLinkJourneyTest.java
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

Moving conf code to url path instead of param

---

src/main/java/org/ilgcc/app/submission/actions/CheckClientSubmissionForProvider.java

Carl wants to be able to skip filling out most of the form and doing a submit of the submission for testing purposes. This will handle that scenario, which should never ever happen in Prod because in Prod there won't be a confirmation code until after submission.

Handle null submittedAt for testing purposes

---

src/main/java/org/ilgcc/app/submission/actions/ValidateChildrenCCAPStartDate.java
src/test/java/org/ilgcc/app/journeys/CcapStartDateTest.java

https://codeforamerica.atlassian.net/browse/CCAP-394?atlOrigin=eyJpIjoiZjdjMmJlZTc2ZmZjNDFlYmFkNGVhODVjYzFiYzMzNWIiLCJwIjoiaiJ9
Updates validation on CCAP child care start date screen only care about valid date / minimum date.

[CCAP-394] Update ValidateChildrenCCAPStartDate to only check minimum date

---

src/main/resources/messages_es.properties

Re-encoding spanish translations

---

scripts/fix_spanish_encoding.sh

A little script to reencode spanish translations after transifex barfs

---

src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/submit-sign-name.html
src/main/resources/templates/providerresponse/info-review.html
src/main/resources/templates/providerresponse/submit-complete-final.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

CCAP-411
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences-(WIP)?node-id=1-8876&node-type=frame&t=5qF6o0pwoA0lNB4H-0)

Ccap 411 submit provider response

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/providerresponse/contact-info.html
src/main/resources/templates/providerresponse/info-review.html
src/main/resources/templates/providerresponse/info.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-382
Adds provider info, contact-info and info-review screens

Add provider info screens

---

src/main/java/org/ilgcc/app/config/DocumentTransferConfiguration.java
src/main/java/org/ilgcc/app/submission/actions/SendUploadedFileToDocumentTransferService.java
src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3.java
src/main/resources/application.yaml

[CCAP-419] Removing flag for enabling background jobs

---

src/main/resources/templates/providerresponse/submit-complete-final.html

CCAP-411
This updates the PR to include the notice

CCAP-411 Updated PR to include notice

---

src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobFlagOffTest.java
src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobFlagOnTest.java

Changes cron job to hourly

---

src/main/resources/messages.properties
src/main/resources/templates/fragments/inputs/screenWithOneInputAndSkip.html
src/main/resources/templates/gcc/offboarding-no-provider.html

- add id links to pages in CCAP-401

[CCAP-401] - implement mixpanel tracking additional fam screens

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/complete-next-steps.html
src/main/resources/templates/gcc/complete-notice.html
src/main/resources/templates/gcc/contact-provider-info.html
src/main/resources/templates/gcc/contact-provider-intro.html

Creates basic outline of screens

---

src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3.java

- From conversation: https://cfastaff.slack.com/archives/C0648BQM6UX/p172860450690056

Add postfix to background job that sends application immediately

---

src/main/resources/templates/gcc/submit-next-steps.html

Fixes for Carl's comments here:
https://codeforamerica.atlassian.net/browse/CCAP-405?focusedCommentId=12678

[CCAP-405] Fixes small issues pointed out by carl in the ticket

---

src/main/java/org/ilgcc/app/data/importer/ProviderImporter.java

Importer tweaks to make the batches larger and excluded rows

---

src/main/java/org/ilgcc/app/data/importer/ProviderImporter.java

Making data importer handle updates

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/providerresponse/confirm-address.html
src/main/resources/templates/providerresponse/info.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

CCAP-383
Adds Smarty validation for provider response flow provider address.

[CCAP-383] Implement provider response flow confirm-address screen

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/resources/templates/gcc/onboarding-provider-info.html
src/test/java/org/ilgcc/app/journeys/FamilyProviderOnboardingScreensTest.java

[The ticket scope](https://codeforamerica.atlassian.net/browse/CCAP-398) is to add email and phone number validations for the provider flow but I added validations for all emails and phone numbers.

[CCAP-398] - validate provider info

---

src/main/resources/templates/fragments/inputs/overrides/number.html

[CCAP-397] Quick fix to only allow numbers

---

src/main/resources/application-dev.yaml

making dev not check the provider db

---

src/main/java/org/ilgcc/app/submission/actions/CheckClientSubmissionForProvider.java
src/main/java/org/ilgcc/app/submission/actions/SaveApplicationIdFromApplicationId.java
src/main/java/org/ilgcc/app/submission/actions/ValidateConfirmationCodeAndSaveId.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderNumber.java
src/main/java/org/ilgcc/app/submission/conditions/IsConfirmationCodeActive.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties

https://codeforamerica.atlassian.net/browse/CCAP-359
https://codeforamerica.atlassian.net/browse/CCAP-437

[CCAP-359][CCAP-437] Handle application already submitted, responded to, and/or invalid confirmation code on providerresponse/application-id screen

---

src/main/resources/templates/providerresponse/submit-start.html

Return home link takes you to home page not FAQ

---

src/main/resources/templates/fragments/inputs/zipcode.html

[CCAP-398] - Changes the zipcode type to numeric

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/resources/pdf-map.yaml
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java

[CCAP-385] - map additional inputs

---

src/main/resources/application-production.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml

CCAP-428
Create a feature flag to control the presentation of the no-provider flow

[CCAP-428]

---

src/main/resources/templates/providerresponse/info.html

[CCAP-398] - Update address in info screen to use address override

---

src/main/java/org/ilgcc/app/ProviderResponsePdfController.java
src/main/resources/templates/fragments/toolbar.html
src/main/resources/templates/providerresponse/application-id.html

CCAP-434
Make it so provider response flow downloads entire family application PDF with family and provider information.

[CCAP-434] Allow PDF downloads in provider response flow

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/actions/SaveApplicationId.java
src/main/java/org/ilgcc/app/submission/actions/ValidateConfirmationCodeAndSaveId.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

Tests for CCAP-359 and CCAP-437

---

src/main/java/org/ilgcc/app/data/Provider.java
src/main/java/org/ilgcc/app/data/importer/ProviderImporter.java
src/main/resources/application-dev.yaml
src/main/resources/db/migration/V2024.11.13.16.35.00__Update_providers_add_approval_date.sql

We need to import the Date Of Last Approval for all providers from the csv. This PR will add the new column, update the generated sql, and also update the Provider object. 
I ran this on Development against the entire csv dataset with no errors. 
I then checked the DB for a randomly selected provider id:
I then looked in the csv to see if that was accurate:
And then I stepped into the code using the debugger and confirmed it looks properly from the db:
All 3 had the same correct date of January 24, 2017.
https://codeforamerica.atlassian.net/browse/CCAP-472

[CCAP-472] Updating ProviderImporter to import Date Of Last Approval for all providers

---

src/main/resources/templates/fragments/head.html

Forgot to commit this version of the file without the apostrophes

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-parent-intro.html
src/main/resources/templates/gcc/children-info-intro.html
src/main/resources/templates/gcc/parent-info-intro.html
src/main/resources/templates/gcc/submit-intro.html
src/main/resources/templates/gcc/unearned-income-intro.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

CCAP-406
Update intro section numbers to include new sections.  Also test to catch changes in section numbers.  
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=11016-30030&t=c9eTSxrw44NROFCL-4)
- Update each string on the intro screens to say “Step N of 6” instead of “..of 5”
- Strings:

[CCAP-406] Update Intro Section Numbers

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3.java
src/main/java/org/ilgcc/app/submission/conditions/NoProviderChosenAndShowNoProviderFlow.java
src/main/java/org/ilgcc/app/submission/conditions/NoProviderChosenAndShowProviderFlagIsOff.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerNoProviderChosenTest.java

CCAP-432
Send application immediately and map no provider selected fields when no provider is chosen

[CCAP-432] Send application immediately and map no provider selected fields when no provider is chosen

---

src/main/resources/application-production.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml

CCAP-483
Add a feature flag to control the display of the new provider flow

[CCAP-483] Add feature flag

---

src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/confirmation-code.html
src/main/resources/templates/providerresponse/registration-family-response-intro.html
src/main/resources/templates/providerresponse/service-address.html

[CCAP-492] - Scaffold application response

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/actions/SetCCRRName.java
src/main/java/org/ilgcc/app/submission/actions/ValidateZipCode.java
src/main/java/org/ilgcc/app/submission/conditions/ShowNoProviderFlow.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/doc-upload-recommended-docs.html
src/main/resources/templates/gcc/next-steps-pdf-delivery.html
src/main/resources/templates/gcc/no-provider-intro.html
src/main/resources/templates/gcc/no-provider-notice.html
src/main/resources/templates/gcc/submit-complete.html
src/main/resources/templates/gcc/submit-next-steps.html
src/test/java/org/ilgcc/app/journeys/FamilyProviderOnboardingScreensTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/NoProviderJourneyWithExpandedFlowFlagTest.java

[Jira Ticket](https://codeforamerica.atlassian.net/browse/CCAP-431)
- Implement No Provider Flow
- Add tests

[CCAP-431] - Implement alternative flow when No Provider is selected

---

src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/doc-upload-head.html
src/main/resources/templates/fragments/head.html
src/main/resources/templates/gcc/doc-upload-add-files.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/utils/Page.java

CCAP-310
Resolves the issue and adds to journey test a check for the regression.

[CCAP-310] Fixes CCAP 310 with additional changes / check for the regression that was found

---

src/main/java/org/ilgcc/app/submission/conditions/EnableProviderRegistration.java
src/main/resources/application-production.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-applicant.html
src/main/resources/templates/providerresponse/registration-getting-started.html
src/main/resources/templates/providerresponse/registration-licensed-care-location.html
src/main/resources/templates/providerresponse/registration-licensing-info.html
src/main/resources/templates/providerresponse/registration-licensing.html
src/main/resources/templates/providerresponse/registration-provider-care-intro.html
src/main/resources/templates/providerresponse/registration-unlicensed-care-location.html
src/main/resources/templates/providerresponse/registration-unlicensed-relationship.html

- changed the default value to 
ALLOW_PROVIDER_REGISTRATION_FLOW in all environments to false.

[CCAP-488] - scaffold provider type

---

src/main/resources/messages.properties

Nov 19 2024 transifex english copy

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/toolbar.html
src/main/resources/templates/index.html

https://codeforamerica.atlassian.net/browse/CCAP-499

[CCAP-499] updating hardcoded alt text to use translatable assets

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/conditions/IsPaidByCCAP.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/providerresponse/paid-by-ccap.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseAllowProviderRegistrationFlagOnJourneyTest.java

CCAP-452
Add paid-for-ccap screen and tests with element id's for each button and/or link on the page.  
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences-(WIP)?node-id=1448-20273&t=GHbWdMur4Bhsh4Gb-4)

[CCAP-452] - create new providerresponse paid by ccap screen

---

src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-start.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseAllowProviderRegistrationFlagOnJourneyTest.java

[CCAP-473] - Add registration start screen and tests

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/conditions/BasicCondition.java
src/main/java/org/ilgcc/app/submission/conditions/HasAdultDependents.java
src/main/java/org/ilgcc/app/submission/conditions/HasSupportedZipCode.java
src/main/java/org/ilgcc/app/submission/conditions/IsPaidByCCAP.java
src/main/java/org/ilgcc/app/submission/conditions/ParentHasPartner.java
src/main/java/org/ilgcc/app/submission/conditions/ParentPartnerQualifies.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderAgreedToCare.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderIsLicensed.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/gcc-icons.html
src/main/resources/templates/providerresponse/registration-licensing.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseAllowProviderRegistrationFlagOnJourneyTest.java

[CCAP-481](https://codeforamerica.atlassian.net/browse/CCAP-481)
- Add registration-licensing screen with yes/no logic
- Update conditions to inherit from basic condition and therefore be more readable
- Add tests for the screen
[Link to Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1448-21077&m=dev)
[CCAP-481]: https://codeforamerica.atlassian.net/browse/CCAP-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-481] - registration licensing screens

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/pdf-map.yaml
src/main/resources/templates/fragments/gcc-icons.html
src/main/resources/templates/providerresponse/registration-basic-info-intro.html
src/main/resources/templates/providerresponse/registration-licensed-care-location.html
src/main/resources/templates/providerresponse/registration-licensing-info.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseAllowProviderRegistrationFlagOnJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOffTest.java
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

CCAP-456 and CCAP-457

---

src/main/java/org/ilgcc/app/data/ProviderRepository.java
src/main/java/org/ilgcc/app/data/ProviderRepositoryService.java

Marc ccap 439

---

src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-tax-id-ein.html

[CCAP-491] - add tax ein

---

build.gradle
src/main/resources/templates/fragments/inputs/overrides/number.html
src/main/resources/templates/fragments/inputs/overrides/phone.html
src/main/resources/templates/fragments/inputs/radioFieldset.html
src/main/resources/templates/fragments/inputs/timeRange.html
src/main/resources/templates/fragments/inputs/zipcode.html
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java

Updating FFL to 1.5.2

---

src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderNumber.java
src/main/resources/application-dev.yaml
src/main/resources/application.yaml
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
src/test/resources/application-test.yaml

https://codeforamerica.atlassian.net/browse/CCAP-545

[CCAP-545] Update fake provider importer to work in dev and test, test cases, and remove flag

---

build.gradle
src/test/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3Test.java
src/test/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3Test.java
src/test/java/org/ilgcc/app/utils/AbstractMockMvcTest.java
src/test/java/org/ilgcc/jobs/PdfTransmissionJobTest.java
src/test/java/org/ilgcc/jobs/UploadedDocumentTransmissionJobTest.java

updating ffl and spring boot to 3.4.0

---

src/main/resources/templates/gcc/contact-provider-message.html

CCAP-549
Fix issue where email would open in same window.

[CCAP-549] Open email in new tab on contact-provider-message screen

---

src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java

Adding the fake providers to Staging

---

src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java

Wrapping with existence checks

---

src/main/resources/application.yaml
src/main/resources/templates/fragments/head.html

https://codeforamerica.atlassian.net/browse/CCAP-289

[CCAP-289] Putting version and commit sha into header

---

src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-confirm-address.html
src/main/resources/templates/providerresponse/registration-confirm-mailing-address.html
src/main/resources/templates/providerresponse/registration-contact-info.html
src/main/resources/templates/providerresponse/registration-info-review.html
src/main/resources/templates/providerresponse/registration-info.html
src/main/resources/templates/providerresponse/registration-mailing-address.html
src/main/resources/templates/providerresponse/registration-service-address.html
src/main/resources/templates/providerresponse/registration-start-date.html
src/main/resources/templates/providerresponse/resgistration-confirm-address.html

CCAP-555
Updates screens, screen names, flows-configs.  This fixes the bug of the notice being triggered in testing when testers arrive at `submit-complete-final`
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1447-28356&t=rGX1Gu8nSWiHbIQg-4)

[CCAP-555] - Bug mitigated and Pages added to provider response

---

src/main/resources/application.yaml
src/main/resources/templates/fragments/head.html

trying to debug header stuff

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java

[CCAP-464] Fixing error messages to be more specific

---

src/main/resources/static/assets/css/custom.css

where did the disabled class go?

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/resources/flows-config.yaml

[CCAP-559] - Resolves PDF Mapping issue

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

TBD if we need this, awaiting Carlie's approval in Slack

[CCAP-464] Consolidation of error messages

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

Error messages for mailing address were using the old message that includes "Please xxxx" so updated to use the most current error messages
No Design Reference. It was not in the Content Manager but these are the error messages used for service manager. Isabel flagged the mis match.

[CCAP-464] - Update error messages to match new messaging

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/faq.html
src/main/resources/templates/index.html

https://codeforamerica.atlassian.net/browse/CCAP-512
https://codeforamerica.atlassian.net/browse/CCAP-562

[CCAP-512][CCAP-562] Homepage and FAQ updates for SDA2 w/ flag logic

---

build.gradle

Not sure how this happened, but this was being included 2x

---

src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-checks-trainings-intro.html
src/main/resources/templates/providerresponse/registration-checks-trainings-notice.html
src/main/resources/templates/providerresponse/registration-convictions-info.html
src/main/resources/templates/providerresponse/registration-convictions.html
src/main/resources/templates/providerresponse/registration-household-add-person-info.html
src/main/resources/templates/providerresponse/registration-household-add-person.html
src/main/resources/templates/providerresponse/registration-household-delete-person.html
src/main/resources/templates/providerresponse/registration-household-members.html

[CCAP-522](https://codeforamerica.atlassian.net/browse/CCAP-522)
[CCAP-522]: https://codeforamerica.atlassian.net/browse/CCAP-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-522] - scaffold background checks and training

---

README.md

[CCAP-569] Updating readme

---

src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-checks-trainings-intro.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

[CCAP-515](https://codeforamerica.atlassian.net/browse/CCAP-515)
- Create intro to registrations screen
- Added journey tests
[Figma Design](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1448-23323&t=9OqSVaPAWl0TKWaz-4)
[CCAP-115]: https://codeforamerica.atlassian.net/browse/CCAP-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCAP-515]: https://codeforamerica.atlassian.net/browse/CCAP-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-515] - Create registration intro screen and tests

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderHasConviction.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/pdf-map.yaml
src/main/resources/templates/providerresponse/registration-convictions-info.html
src/main/resources/templates/providerresponse/registration-convictions.html
src/main/resources/templates/providerresponse/registration-household-members.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java

[CCAP-518](https://codeforamerica.atlassian.net/browse/CCAP-518)
- Create registrations convictions screen
- Conditionally display the following screen depending on the answer
- Add journey and preparer tests
- Map data to the PDF
[Link to figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1448-23130&t=Fh85svjkhRTV3Bhq-4)
[CCAP-518]: https://codeforamerica.atlassian.net/browse/CCAP-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-518] - registration convictions screen

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/java/org/ilgcc/app/submission/conditions/HasRegistrationHouseholdMembers.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderHouseholdRegistrationRequired.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/pdf-map.yaml
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/providerresponse/registration-convictions-info.html
src/main/resources/templates/providerresponse/registration-family-response-intro.html
src/main/resources/templates/providerresponse/registration-household-add-person.html
src/main/resources/templates/providerresponse/registration-household-members.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

[CCAP-519](https://codeforamerica.atlassian.net/browse/CCAP-519)
[CCAP-520](https://codeforamerica.atlassian.net/browse/CCAP-520)
- Implement Convictions info screen
- Implement Question on whether someone has a household member
- Add relevant tests
[CCAP-519]: https://codeforamerica.atlassian.net/browse/CCAP-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCAP-520]: https://codeforamerica.atlassian.net/browse/CCAP-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-519] - registration convictions info screen

---

src/main/java/org/ilgcc/app/submission/conditions/ProviderIsRegistering.java
src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-signature.html
src/main/resources/templates/providerresponse/registration-submit-complete.html
src/main/resources/templates/providerresponse/registration-submit-intro.html
src/main/resources/templates/providerresponse/registration-submit-next-steps.html
src/main/resources/templates/providerresponse/registration-terms.html

[CCAP-530](https://codeforamerica.atlassian.net/browse/CCAP-530)
Creates screens:
- providerresponse/registration-submit-intro
- providerresponse/registration-terms
- providerresponse/registration-signature
- providerresponse/registration-submit-complete
- providerresponse/registration-submit-next-steps
Adds a check for whether the person is in the registration process
[CCAP-530]: https://codeforamerica.atlassian.net/browse/CCAP-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-530] - Scaffolds sign and submit screens

---

src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/inputs/checkboxFieldset.html
src/main/resources/templates/fragments/inputs/radioFieldset.html

https://codeforamerica.atlassian.net/browse/CCAP-573

[CCAP-573] Handle error messages when no label is set on the surrounding block

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties

Updating copy for error message

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/gcc/children-info-basic.html

[CCAP-588] removing helper text

---

.github/workflows/run-percy.yaml

- Updates percy configuration so that we test provider flow and provider registration

Expands percy to include new flows

---

src/main/java/org/ilgcc/app/submission/actions/RemoveIncompleteChildIterations.java
src/main/java/org/ilgcc/app/submission/actions/SaveCCAPStartDate.java

trying this out

---

src/main/java/org/ilgcc/app/email/EmailConstants.java
src/main/java/org/ilgcc/app/email/SendGridEmailService.java
src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmail.java
src/main/java/org/ilgcc/jobs/SendEmailJob.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties

https://codeforamerica.atlassian.net/browse/CCAP-495

[CCAP-495] Translating confirmation email sender name

---

.github/workflows/deploy-to-staging.yaml

trying something out for staging deploys

---

.github/workflows/deploy-to-staging.yaml

Marc stg deploy

---

src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java

[CCAP-609] Adjusting the logging for No Provider job

---

src/main/java/org/ilgcc/jobs/SendEmailJob.java
src/main/resources/application-demo.yaml
src/main/resources/application-dev.yaml
src/main/resources/application-production.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml
src/test/resources/application-test.yaml

https://codeforamerica.atlassian.net/browse/CCAP-611

[CCAP-611] Feature flagging email sending, to disable in dev, test, and demo by default

---

src/main/java/org/ilgcc/app/email/SendGridWebhookController.java
src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
src/main/java/org/ilgcc/app/utils/TextUtilities.java

[CCAP-613] Cleanup to reduce Sentry errors

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/pdf/NeedChildcareForChildren.java
src/main/java/org/ilgcc/app/pdf/ProviderAndFamilyPreparer.java
src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/java/org/ilgcc/app/pdf/ProviderSSNPreparer.java
src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparer.java
src/main/java/org/ilgcc/app/pdf/ProviderTypePreparer.java
src/main/java/org/ilgcc/app/submission/actions/CreateProviderCareStartDate.java
src/main/java/org/ilgcc/app/submission/actions/SetProviderCareStartDate.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderCareStartDate.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-start-date.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ProviderAndFamilyPreparerTest.java

[CCAP-471](https://codeforamerica.atlassian.net/browse/CCAP-471)
- implements registration-start-date screen
- if family has provided ccap start date, it will preload the earliest ccap start date
- if the family has not provided a start date, no data is preloaded
- Once the provider adds/confirms date there will be validation that confirms:
- value is after 1/1/12910
- value is valid
- value is present
[CCAP-471]: https://codeforamerica.atlassian.net/browse/CCAP-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-471] - Create a provider care start date and screen

---

src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparer.java

[CCAP-613] Sentry error cleanup

---

src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-submit-intro.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

[CCAP-525] creating new providerresponse/registration-submit-intro screen

---

src/main/java/org/ilgcc/app/email/SendGridWebhookController.java

[CCAP-612] Enhancing sendgrid webhook logging in error state

---

src/main/resources/flows-config.yaml

[CCAP-617] send confirmation email on page render, not on page exit

---

src/main/java/org/ilgcc/app/ProviderResponsePdfController.java

[CCAP-619] Cleaning up sentry error on pdf download

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-608

[CCAP-608] Include confirmation code for no provider response and no provider selected

---

src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-doc-upload-add-files.html
src/main/resources/templates/providerresponse/registration-doc-upload-recommended-docs.html
src/main/resources/templates/providerresponse/registration-doc-upload-submit-confirmation.html

[CCAP-535](https://codeforamerica.atlassian.net/browse/CCAP-535)
- scaffolds screens
[CCAP-535]: https://codeforamerica.atlassian.net/browse/CCAP-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-535] - Scaffold provider upload documents

---

src/main/resources/application.yaml

[CCAP-628](https://codeforamerica.atlassian.net/browse/CCAP-628)
- adds new feature flag
- Set ENABLE_SDA15_PROVIDERS to false in heroku
- Set ENABLE_SDA15_PROVIDERS to false in aptible staging
- Set ENABLE_SDA15_PROVIDERS to false in aptible prod
[CCAP-628]: https://codeforamerica.atlassian.net/browse/CCAP-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-628] - Add SDA15 expansion feature flag

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/pdf/ProviderHouseholdMemberPreparer.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderHouseholdMemberBirthday.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/pdf-map.yaml
src/main/resources/templates/gcc/parent-add-adults.html
src/main/resources/templates/providerresponse/registration-household-add-person-info.html
src/main/resources/templates/providerresponse/registration-household-add-person.html
src/main/resources/templates/providerresponse/registration-household-delete-person.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ProviderHouseholdMemberPreparerTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

CCAP-521
Should map to fields in the PDF, see CCAP-521
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1448-23393&t=T72ynXLvePyyC1Yd-4)
[Content Mangager](https://docs.google.com/document/d/1ERZ8oqKu_K1HCdm8wQMgCDyYJR-3xF8-d8t7LK84Hmo/edit?tab=t.0#bookmark=id.7pxy9j711oga)

[CCAP-521] create provider household member subflow

---

src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobTest.java

[CCAP-635] Updated logic for checking is provider response as a submitted_at date

---

build.gradle

https://codeforamerica.atlassian.net/browse/CCAP-639

[CCAP-639] Not able to upload valid MS Word doc

---

src/main/java/org/ilgcc/app/config/DocumentTransferConfiguration.java
src/main/java/org/ilgcc/app/file_transfer/DocumentTransferRequestService.java
src/main/java/org/ilgcc/app/submission/router/CCRR.java
src/main/java/org/ilgcc/app/utils/enums/FileNameUtility.java
src/test/java/org/ilgcc/app/file_transfer/DocumentTransferRequestServiceTest.java

[CCAP-623] - route dts on ccrr

---

build.gradle

[CCAP-639] Bumping FFL version to handle a Tika mime type mismatch issue

---

build.gradle

[CCAP-639] Another docx mimetype issue

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/providerresponse/registration-submit-next-steps.html

CCAP-529
Generate CCAP-529 Screen with appropriate text and icons.  
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1448-24004&m=dev)

CCAP-529 Created registration-submit-next-steps.html screen

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/fragments/inputs/overrides/fileUploader.html
src/main/resources/templates/providerresponse/registration-doc-upload-add-files.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

CCAP-532
***CCAP 532***
Added `registration-doc-upload-add-files` screen.  This screen will allow us to upload files and display the recommended docs the provider should upload.
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1448-24146&m=dev)

[CCAP-532] - create new providerresponse registration doc upload add files screen

---

Dockerfile
build.gradle
scripts/setup.sh
src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmail.java
src/main/resources/application.yaml
src/test/java/org/ilgcc/jobs/UploadedDocumentTransmissionJobTest.java

https://codeforamerica.atlassian.net/browse/CCAP-575
https://codeforamerica.atlassian.net/browse/CCAP-629
This is basically just a FFL version upgrade, plus setting up LibreOffice in dev and in Docker/Aptible. Also, a small tweak on some logging.

[CCAP-629][CCAP-575] Convert images and documents to PDF

---

src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java

CCAP-604
Update List of [Illinois holidays](https://cms.illinois.gov/personnel/employeeresources/stateholidays.html) to include 2026 holidays

[CCAP-604] Added 2026 State holidays

---

src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-signature.html

[CCAP-527] Fixed the label for input test

---

src/main/java/org/ilgcc/app/utils/CountyOptionUtils.java

[CCAP-509] fixing order for county

---

build.gradle
src/main/resources/application-staging.yaml

[CCAP-629][CCAP-575] Allowing file transfer size to be different than file upload size in staging for testing

---

build.gradle
src/main/resources/application-staging.yaml

[CCAP-629][CCAP-575] Allowing the number of pages on pdf conversion to be configurable for testing

---

src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-doc-upload-submit-confirmation.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java

[CCAP-533] Add new provider registration doc upload confirmation screen

---

.github/workflows/deploy-to-prod.yaml
.github/workflows/deploy-to-staging.yaml

Reverts codeforamerica/il-gcc-form-flow#1135

Revert "Bump getsentry/action-release from 1 to 2"

---

src/main/resources/templates/fragments/mixpanelTracking.html

https://codeforamerica.atlassian.net/browse/CCAP-658

[CCAP-658] Track family confirmation code for provider visits

---

src/main/resources/messages.properties

[CCAP-669] Fixing spelling of Fayette

---

build.gradle

All the work was done in https://github.com/codeforamerica/form-flow/pull/658/

[CCAP-670] Enhance file conversion service to retry up to 10 times if LibreOffice fails

---

src/main/java/org/ilgcc/app/config/CCMSApiConfiguration.java
src/main/java/org/ilgcc/app/data/api/CCMSApiClient.java
src/main/resources/application-dev.yaml

CCAP-644
Successful request to Work Item fetch endpoint:

[CCAP-644] Implement CCMSApiClient with method for sending requests to CCMS

---

src/main/java/org/ilgcc/app/data/Provider.java
src/main/java/org/ilgcc/app/data/ResourceOrganization.java
src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/main/java/org/ilgcc/app/utils/ZipcodeOption.java

https://codeforamerica.atlassian.net/browse/CCAP-671
Noticed some easy CodeQL warnings in Github to clean up. Most were false positives, but these were easy to fix. Will comment on each file with a link to the issue.

[CCAP-671] Clean up for a few CodeQL warnings in github

---

scripts/jobrunr_dashboard_launcher.sh
scripts/webapp_launcher.sh
src/main/resources/application.yaml

[CCAP-626] Disable jobrunr server on web container and dashboard

---

src/main/java/org/ilgcc/app/data/importer/ProviderImporter.java

[CCAP-640] Adding resource org id to provider data importer

---

src/main/java/org/ilgcc/app/data/CCMSDataServiceImpl.java
src/main/java/org/ilgcc/app/data/ResourceOrganization.java
src/main/java/org/ilgcc/app/data/importer/ResourceOrganizationImporter.java
src/main/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRName.java
src/main/resources/db/migration/V2025.02.19.01.12.00__Update_resource_org_add_address_fields.sql
src/test/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRNameTest.java

https://codeforamerica.atlassian.net/browse/CCAP-640

[CCAP-640] Resource Organization data importer

---

src/main/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmail.java

[CCAP-642] - Missing annotation in Action

---

src/main/java/org/ilgcc/app/submission/actions/CheckFamilySubmissionForProvider.java
src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
src/main/java/org/ilgcc/app/submission/actions/FormatChildrenWhoNeedCareNames.java
src/main/java/org/ilgcc/app/submission/actions/GenerateDummyFamilySubmissionForDev.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderAgreesToCareFamilyConfirmationEmail.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmail.java
src/main/java/org/ilgcc/app/submission/actions/SetProviderCareStartDate.java
src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/resources/flows-config.yaml

https://codeforamerica.atlassian.net/browse/CCAP-682

[CCAP-682] Further changes to rid ourselves of the client terminology

---

src/main/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmail.java
src/main/resources/flows-config.yaml

Skips email send when recipient email is blank

---

src/main/java/org/ilgcc/app/file_transfer/DocumentTransferRequest.java
src/main/java/org/ilgcc/app/file_transfer/DocumentTransferRequestService.java
src/main/java/org/ilgcc/jobs/PdfTransmissionJob.java
src/main/java/org/ilgcc/jobs/UploadedDocumentTransmissionJob.java
src/test/java/org/ilgcc/jobs/UploadedDocumentTransmissionJobTest.java

https://codeforamerica.atlassian.net/browse/CCAP-683
Fixes https://github.com/codeforamerica/il-gcc-form-flow/security/code-scanning/860

[CCAP-683] Cleanup Github security alert for deprecated constructor

---

src/main/java/org/ilgcc/app/submission/actions/SendProviderAgreesToCareFamilyConfirmationEmail.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmail.java

[CCAP-684] - Adds new logic for provider and family confirmation emails

---

src/main/java/org/ilgcc/app/data/Transaction.java
src/main/java/org/ilgcc/app/data/TransactionRepository.java
src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
src/main/resources/db/migration/V2025.02.21.15.34.55__Add_transcations_table.sql

CCAP-592
Creates `Transaction` entity, `TransactionRepository` interface and `TransactionRepositoryInterface` service layer.
Adds a migration for the new table.

[CCAP-592] Create transaction storage classes and migration

---

build.gradle
sample.env
src/main/resources/application-demo.yaml
src/main/resources/application-dev.yaml
src/main/resources/application-production.yaml
src/main/resources/application.yaml
src/test/resources/application-test.yaml

Adding keys to sample.env

---

src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmail.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderAgreesToCareFamilyConfirmationEmail.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmail.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/test/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/submission/actions/SendProviderAgreesToCareFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/submission/actions/SendProviderConfirmationEmailTest.java

[CCAP-667] -  more changes to email refactor

---

src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmail.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/test/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmailTest.java

[CCAP-667] - link input name is called shareable link

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/onboarding-provider-info-confirm.html

CCAP-695
Change copy and icon for the onboarding-provider-info-confirm.title screen
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=16316-24344&m=dev)
[Content Manager](https://docs.google.com/document/d/1vwtwI1-GcqrGDGf3l1UEk161ahoGqVlCAX0BhmoYnlY/edit?tab=t.0#bookmark=id.ebng66rb363x)

[CCAP-695] Update onboarding-provider-info-confirm.html screen

---

build.gradle
src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/application-dev.yaml
src/main/resources/application-staging.yaml

https://codeforamerica.atlassian.net/browse/CCAP-598

[CCAP-598] Require SSN to be actually valid

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/fragments/cardHeader.html
src/main/resources/templates/gcc/contact-provider-message.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-696

[CCAP-696] Change copy on the contact-provider-message page

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/screens/registration-submit-confirmation.html

[CCAP-672] - fixes copy

---

src/main/resources/templates/gcc/onboarding-provider-info-confirm.html

[CCAP-695] Fixing spacing

---

.gitignore
src/main/java/org/ilgcc/app/data/CCMSDataService.java
src/main/java/org/ilgcc/app/data/CCMSDataServiceImpl.java
src/main/java/org/ilgcc/app/data/Provider.java
src/main/java/org/ilgcc/app/data/importer/CountyAndZipCodeImporter.java
src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java
src/main/java/org/ilgcc/app/data/importer/ImporterUtils.java
src/main/java/org/ilgcc/app/data/importer/ProviderImporter.java
src/main/java/org/ilgcc/app/data/importer/ResourceOrganizationImporter.java
src/main/java/org/ilgcc/app/submission/router/ApplicationRouterService.java
src/main/java/org/ilgcc/app/submission/router/ApplicationRoutingServiceImpl.java
src/main/resources/db/migration/V2025.03.06.13.54__Update_providers_add_site_provider_org_id.sql
src/test/java/org/ilgcc/app/data/ProviderAndResourceOrganizationIntegrationTest.java
src/test/java/org/ilgcc/app/data/ProviderAndSiteAdministeredResourceOrganizationTest.java
src/test/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRNameTest.java

https://codeforamerica.atlassian.net/browse/CCAP-704

[CCAP-704] Update provider table and provider importer to support site-administered provider orgs

---

src/main/java/org/ilgcc/app/submission/actions/SendUploadedFileToDocumentTransferService.java
src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayload.java
src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java

Not related to any ticket. 
Just missed a spot where the flag to run Document Transfer Service calls should have been added.

Don't run DTS jobs if feature flag is off

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/app/submission/actions/GenerateDummyFamilySubmissionForDev.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java
src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayload.java
src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java

[CCAP-675] Send provider registration supporting documents with family submission to CCMS

---

src/main/resources/static/assets/css/custom.css
src/main/resources/templates/index.html

[CCAP-647]
Fixes display issues including:
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8?type=design&node-id=15859%3A18494&mode=dev)
[CCAP-647]: https://codeforamerica.atlassian.net/browse/CCAP-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-647] Update provider response section

---

src/main/resources/templates/index.html

[CCAP-647]
Reduce the space between the label and text box
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=15859-18494&m=dev)
[CCAP-647]: https://codeforamerica.atlassian.net/browse/CCAP-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-647] changed spacing to 25 between label and textbox

---

build.gradle

[CCAP-726] If address validation fails due to an error, return an empty map and log an error

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransaction.java
src/main/java/org/ilgcc/app/utils/FileNameUtility.java

https://codeforamerica.atlassian.net/browse/CCAP-709

[CCAP-709] Truncate First Name and Last Name in CCMS API Submission Request

---

src/main/java/org/ilgcc/app/utils/FileNameUtility.java
src/test/java/org/ilgcc/app/utils/FileNameUtilityTest.java

https://codeforamerica.atlassian.net/browse/CCAP-718
Updated the method to include the confirmation code aka the short code. Also added a test that confirms the new path is as requested.

[CCAP-718] Include client confirmation code as part of folder name in sharepoint

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
src/main/java/org/ilgcc/jobs/TransactionWorkItemRecurringJob.java

This PR adds better logging and error handling around the work item lookup job.

Improve logging and error handling on work item look up job

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/gcc/onboarding-2-part.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccNoProviderFlowJourneyTest.java

[CCAP-721]
Submit into 
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=17178-42553&t=prDittHGEvVo4eJf-4)
[Content Manager](https://docs.google.com/document/d/1vwtwI1-GcqrGDGf3l1UEk161ahoGqVlCAX0BhmoYnlY/edit?tab=t.0#bookmark=id.xl4zv8m87fnj)
[CCAP-721]: https://codeforamerica.atlassian.net/browse/CCAP-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-721] Add onboarding-2-part.html screen and update tests

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/submit-contact-method.html
src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java

[CCAP-723](https://codeforamerica.atlassian.net/browse/CCAP-723)
- create submit-contact-method screen and inputName: contactProviderMethod
- Add tests
[CCAP-723]: https://codeforamerica.atlassian.net/browse/CCAP-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-723] - create submit-contact-method screen and corresponding tests

---

src/main/java/org/ilgcc/app/email/SendEmail.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java

updates logs after recent alerts

---

src/main/java/org/ilgcc/app/submission/conditions/IsPaidByCCAP.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderIsRegistering.java
src/main/resources/templates/providerresponse/registration-submit-confirmation.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

Fixes issue when paid by ccap is not set

---

src/main/resources/templates/providerresponse/registration-info-review.html

[CCAP-725](https://codeforamerica.atlassian.net/browse/CCAP-725)
Before:
After:
[CCAP-725]: https://codeforamerica.atlassian.net/browse/CCAP-725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-725] - removes extra line

---

build.gradle

https://codeforamerica.atlassian.net/browse/CCAP-766

[CCAP-766] Submission updated_at field is immutable and needs to be fixed

---

src/main/java/org/ilgcc/jobs/TransactionWorkItemRecurringJob.java

https://codeforamerica.atlassian.net/browse/CCAP-769

[CCAP-769] Reoccuring job needs to recalculate 1 hour ago date every time the job runs

---

src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaText.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/gcc/parent-confirm-provider-number.html
src/main/resources/templates/gcc/submit-confirm-provider-email.html
src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
src/test/java/org/ilgcc/app/submission/conditions/ContactProviderViaTextTest.java
src/test/java/org/ilgcc/app/utils/SeleniumFactory.java

CCAP-741
[Figma Link](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=17162-40991&t=pBauaJFgp3dzS0M9-4)

[CCAP-741] Add parent-confirm-provider-number-screen

---

src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java

Updates error message for TransmissionRecurringJob

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java

https://codeforamerica.atlassian.net/browse/CCAP-776

[CCAP-776] adding some logging for CCMS

---

.github/workflows/deploy-to-qa.yaml

CCAP-690
Adding a workflow to deploy to the AWS QA environment.

[CCAP-690] Add deploy to QA workflow

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
src/main/java/org/ilgcc/app/data/ccms/CCMSTransaction.java

[CCAP-776] tweaking ccms logging

---

src/main/java/org/ilgcc/app/data/TransactionRepository.java
src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobTest.java

https://codeforamerica.atlassian.net/browse/CCAP-774

[CCAP-774] Handle submissions without transmissions because CCMS was the only thing turned on

---

src/main/java/org/ilgcc/app/data/TransactionRepository.java
src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java
src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobTest.java

Reverts codeforamerica/il-gcc-form-flow#1369

Revert "[CCAP-774] Handle submissions without transmissions because CCMS was the only thing turned on"

---

.github/workflows/deploy-to-qa.yaml

[CCAP-690] Tag docker image with latest and specify region in ECS push

---

src/main/resources/application.yaml
src/main/resources/templates/gcc/submit-contact-provider-text-confirmation.html

CCAP-735
Fixes the confirmation code and shareable link issue

[CCAP-735] update

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
src/main/java/org/ilgcc/app/data/ccms/CCMSTransaction.java

[CCAP-776] Removing request logging

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/inputs/Providerresponse.java

[CCAP-785](https://codeforamerica.atlassian.net/browse/CCAP-785)
- Adds missing zip code validation to parent home zip, parent mailing zip, provider home zip, provider service zip
[CCAP-785]: https://codeforamerica.atlassian.net/browse/CCAP-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-785] - validates zip code length.

---

src/main/resources/application.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-parent-intro.html
src/main/resources/templates/gcc/children-info-intro.html
src/main/resources/templates/gcc/contact-provider-intro.html
src/main/resources/templates/gcc/no-provider-intro.html
src/main/resources/templates/gcc/parent-info-intro.html
src/main/resources/templates/gcc/submit-intro.html
src/main/resources/templates/gcc/unearned-income-intro.html

[CCAP-744](https://codeforamerica.atlassian.net/browse/CCAP-744)
- removes hard coded step count strings and use a general string
- sets step count based on feature flag
[CCAP-744]: https://codeforamerica.atlassian.net/browse/CCAP-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-744] - change step count

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/conditions/HasConfirmedProviderPhoneNumber.java
src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/gcc/submit-confirm-provider-email.html
src/main/resources/templates/gcc/submit-confirm-provider-number.html
src/main/resources/templates/gcc/submit-provider-edit-text.html
src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
src/test/java/org/ilgcc/app/submission/conditions/HasConfirmedProviderPhoneNumberTest.java

CCAP-742
[CCAP-741]: https://codeforamerica.atlassian.net/browse/CCAP-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-742] Create new submit-provider-edit-text screen

---

.github/workflows/run-percy.yaml

Reverts codeforamerica/il-gcc-form-flow#1398

Revert "Update run-percy.yaml"

---

src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java

https://codeforamerica.atlassian.net/browse/CCAP-805

[CCAP-805] Able to submit multiple provider responses with same short code

---

src/main/java/org/ilgcc/app/submission/conditions/EnableProviderRegistrationItin.java
src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/main/resources/templates/providerresponse/registration-home-provider-itin.html
src/main/resources/templates/providerresponse/registration-home-provider-tax-id.html
src/main/resources/templates/providerresponse/registration-tax-id-itin.html

[CCAP-780](https://codeforamerica.atlassian.net/browse/CCAP-780)
- creates 3 screens
- adds new feature flag: ENABLE_PROVIDER_REGISTRATION_WITH_ITIN
- Adds the screens to the flows config file in generally the correct place behind the feature flag
[CCAP-780]: https://codeforamerica.atlassian.net/browse/CCAP-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-780] - creates new feature flag and scaffolds new screens

---

src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaEmail.java
src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaOther.java
src/main/java/org/ilgcc/app/submission/conditions/ContactProviderViaText.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/gcc/submit-contact-provider-email-confirmation.html
src/main/resources/templates/gcc/submit-contact-provider-text-confirmation.html
src/main/resources/templates/gcc/submit-share-confirmation-code.html
src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-737
There would be a whole mess of permutations of where this button is shown and not shown, but here's an example:

[CCAP-737] Adjust the CTA on the final provider messaging step

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/fragments/inputs/overrides/fileUploader.html

https://codeforamerica.atlassian.net/browse/CCAP-731
This change should also be added to FFL's version of this file, which I'll do once this is approved and tested, etc. I don't exactly know why we have our own version of this fragment. 
Also, we need translations for this message per the screenshot below.

[CCAP-731] Handle doc upload errors when a users' session is expired

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/providerresponse/registration-doc-upload-recommended-docs.html

https://codeforamerica.atlassian.net/browse/CCAP-743

[CCAP-743] Update the content on the doc-upload-recommended-docs screen

---

src/main/java/org/ilgcc/app/submission/conditions/ShouldSkipConfirmationCode.java

https://codeforamerica.atlassian.net/browse/CCAP-822

[CCAP-822] Save the confirmation code when skipping the confirmation code screen

---

src/main/java/org/ilgcc/app/DocumentUploadController.java
src/test/java/org/ilgcc/app/DocumentUploadControllerTest.java

[CCAP-703] Prevent Additional Document Uploads for Providers

---

src/main/java/org/ilgcc/app/DocumentUploadController.java

[CCAP-703] Use the actual submission id

---

src/main/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJob.java

[CCAP-716] Sets cron job to 4:00 am cst

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/conditions/IsLicensedOrLicenseExemptHomeCareProvider.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-home-provider-tax-id.html

CCAP-778
Add registration-home-provider-tax-id screen.

[CCAP-778] Add registration-home-provider-tax-id.html

---

src/main/resources/templates/providerresponse/registration-home-provider-ssn.html

https://codeforamerica.atlassian.net/browse/CCAP-781
With the flag off:
With the flag on:

[CCAP-781] Update providerresponse/registration-home-provider-ssn screen

---

build.gradle

This will update to Amazon SDK v2, and also fix the two Sentry errors.
https://codeforamerica.atlassian.net/browse/CCAP-767
https://codeforamerica.atlassian.net/browse/CCAP-828
https://codeforamerica.atlassian.net/browse/CCAP-829

[CCAP-767][CCAP-828][CCAP-829] FFL upgrade to move to Amazon sdk v2, clean up minor other bugs

---

src/main/java/org/ilgcc/app/data/CCMSDataServiceImpl.java
src/main/java/org/ilgcc/app/data/TransactionRepository.java
src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
src/main/java/org/ilgcc/app/email/templates/DailyNewApplicationsProviderEmailTemplate.java
src/main/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJob.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/email/SendAutomatedProviderOutreachEmailTest.java

[CCAP-716] follow on work

---

src/test/java/org/ilgcc/app/journeys/ProviderResponseShortLinkJourneyTest.java
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java

[CCAP-834] Improving the ProviderResponse tests

---

src/main/resources/application.yaml

[CCAP-837] Updating Hikari settings

---

src/main/java/org/ilgcc/app/email/SendGridEmailValidationService.java

[CCAP-711] Making error logging consistent for alerting purposes

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/conditions/IsLicensedOrLicenseExemptHomeCareProvider.java
src/main/java/org/ilgcc/app/submission/conditions/selectedITIN.java
src/main/java/org/ilgcc/app/submission/conditions/selectedSSN.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-home-provider-itin.html
src/test/java/org/ilgcc/app/utils/SeleniumFactory.java

[CCAP-782] Add registration-home-provider-itin.html

---

src/main/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJob.java
src/main/java/org/ilgcc/jobs/SendRecurringEmailJob.java
src/test/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJobTest.java

stagger email send times by a minute per job

---

src/main/java/org/ilgcc/app/submission/actions/ValidateProviderEmail.java

[CCAP-711] adds a null check for the httpSession.getAttribute method
[CCAP-711]: https://codeforamerica.atlassian.net/browse/CCAP-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-711] validate provider email address

---

src/main/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJob.java
src/main/java/org/ilgcc/jobs/SendRecurringEmailJob.java
src/test/java/org/ilgcc/jobs/TransmissionsRecurringJobTest.java

[CCAP-619] Staggering emails a bit better

---

src/main/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJob.java
src/main/java/org/ilgcc/jobs/SendRecurringEmailJob.java

[CCAP-619] Trying a 15 seconds delay instead of 1 full minute

---

src/main/java/org/ilgcc/app/email/ILGCCEmail.java
src/main/java/org/ilgcc/app/email/SendGridEmailService.java
src/main/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJob.java
src/test/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJobTest.java

[CCAP-619] Adding multi-recipient support for daily emails

---

src/main/resources/messages.properties

[CCAP-619] Email copy changes

---

src/main/java/org/ilgcc/app/email/templates/DailyNewApplicationsProviderEmailTemplate.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/email/SendAutomatedProviderOutreachEmailTest.java

[CCAP-619} More email content updates

---

src/main/resources/messages.properties
src/main/resources/templates/providerresponse/registration-tax-id.html

CCAP-783
Update registration-tax-id.html screen
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=5601-46482&t=qAsdKJ72jpVq3Man-4)

[CCAP-783] Update provider response registration-tax-id.html screen

---

src/main/resources/messages.properties

[CCAP-810] Update paid-by-ccap screen

---

src/main/java/org/ilgcc/app/email/SendGridEmailValidationService.java
src/main/java/org/ilgcc/app/email/SendGridValidationResponseBody.java
src/test/java/org/ilgcc/app/email/SendGridEmailValidationServiceTest.java
src/test/java/org/ilgcc/app/email/SendGridValidationResponseBodyTest.java
src/test/java/org/ilgcc/app/utils/SendGridValidationResponseBodyBuilder.java

[CCAP-711] Removed Suspected bounces from email validation

---

README.md
sample.env

cleaning up some sample.env stuff and the readme

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java

Update logs to include full response and container IP

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java

Enhancing logging for CCMS endpoint responses

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java

Only set the CCMS basic auth if we have a username and password

---

src/main/java/org/ilgcc/app/config/CCMSApiConfiguration.java
src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java
src/main/resources/application.yaml

https://codeforamerica.atlassian.net/browse/CCAP-849
Removing CCMS username and password, since we don't need to use them any more.

[CCAP-849] Removing unused CCMS config values

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java

https://codeforamerica.atlassian.net/browse/CCAP-852
We can skip around in the flow, and that causes NPEs when trying to create a CCMS payload. This shouldn't ever happen in Production but we will set up a Datadog monitor based on this new logging if it does happen!

[CCAP-852] Handling NPEs that happen because we skip around in the flow

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderChoseITINTaxIdType.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationWithITINJourneyTest.java
src/test/java/org/ilgcc/app/submission/conditions/ProviderChoseITINTaxIdTypeTest.java

CCAP-783
Modifies copy and updates conditional logic.  Also changes error message and adds tests to verify the conditional logic and the error copy

[CCAP-783] modify copy and conditional logic

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java

https://codeforamerica.atlassian.net/browse/CCAP-860

[CCAP-860] NPE in ProviderApplicationPreparer

---

src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerTest.java

[CCAP-808](https://codeforamerica.atlassian.net/browse/CCAP-808)
- Adds tests that confirm that providerTaxIdEIN is mapped in the PDF.
[CCAP-808]: https://codeforamerica.atlassian.net/browse/CCAP-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-808] - tests that FEIN is properly set

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/actions/ValidateFEINIsNotBlank.java
src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/inputs/overrides/text.html
src/main/resources/templates/providerresponse/provider-id-fein.html
src/main/resources/templates/providerresponse/registration-tax-id-ein.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

[CCAP-814] Create provider-id-fein screen

---

src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java

https://codeforamerica.atlassian.net/browse/CCAP-866

[CCAP-866] Downgrading logging to a WARN so Sentry stops complaining when we're testing with garbage data

---

src/main/resources/static/assets/css/custom.css
src/main/resources/templates/providerresponse/fein.html

https://codeforamerica.atlassian.net/browse/CCAP-813
Update visual elements to match designs
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=5593-34527&m=dev)
Figma
local
[CCAP-815]: https://codeforamerica.atlassian.net/browse/CCAP-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-813] Updated Screen to match design

---

src/main/resources/templates/providerresponse/info-review.html

https://codeforamerica.atlassian.net/browse/CCAP-884

[CCAP-884] blank dot point for business name when it's not set

---

src/main/java/org/ilgcc/app/ProviderLinkController.java
src/main/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayload.java
src/main/java/org/ilgcc/app/submission/actions/ValidateConfirmationCode.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/java/org/ilgcc/app/utils/enums/SubmissionStatus.java
src/test/java/org/ilgcc/app/submission/actions/UploadSubmissionToS3AndEnqueueCCMSPayloadTest.java

https://codeforamerica.atlassian.net/browse/CCAP-883

[CCAP-883] Prevent No Provider Chosen confirmation codes from proceeding through the provider flow

---

src/main/resources/messages.properties
src/main/resources/templates/providerresponse/submit-confirmation.html

CCAP-816
Fixes a small debugging message that was accidentally left in.

[CCAP-816] Fixes a debugging message that was accidentally left in

---

src/main/resources/flows-config.yaml
src/main/resources/templates/gcc/delete-provider.html
src/main/resources/templates/gcc/providers-add.html
src/main/resources/templates/gcc/providers-all-ccap-children.html
src/main/resources/templates/gcc/providers-chosen.html
src/main/resources/templates/gcc/providers-info-confirm.html
src/main/resources/templates/gcc/providers-info.html
src/main/resources/templates/gcc/providers-intro.html
src/main/resources/templates/gcc/providers-no-provider-intro.html

CCAP-892
1.  Add screens names to flows-config 
2. Run create-templates.sh
3. verify that screens are created

[CCAP-892] Stub out screens for multiple provider add provider work

---

src/main/java/org/ilgcc/app/submission/conditions/EnableMultipleProviders.java
src/main/resources/application.yaml
src/main/resources/flows-config.yaml

[CCAP-874] Add Multiple Provider flag and flows config logic

---

src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java

https://codeforamerica.atlassian.net/browse/CCAP-681
For now, I left `staging` in the list and just added `qa`. No one seemed to have a strong opinion during refinement, and it is helpful (to me, at least) to just be able to enter `012345678901` in Staging at times.

[CCAP-681] Adding qa to the fake data importer

---

src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

[CCAP-804](https://codeforamerica.atlassian.net/browse/CCAP-804) - Show months for children under 2
[[CCAP-752]](https://codeforamerica.atlassian.net/browse/CCAP-752) - Translate days of week when displaying schedule in response screen
[CCAP-804]: https://codeforamerica.atlassian.net/browse/CCAP-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCAP-752]: https://codeforamerica.atlassian.net/browse/CCAP-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-804], [CCAP-752] display months for children under 2 and translate days of week

---

src/main/resources/messages.properties

[CCAP-895]
Changes `providers-no-provider-intro.continue` copy from "Continue without a provider" to "Continue with no provider"
[CCAP-895]: https://codeforamerica.atlassian.net/browse/CCAP-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-895] Fix Small nit

---

src/main/java/org/ilgcc/app/submission/conditions/SkipWhenEnableMultipleProvidersIsEnabled.java
src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java

[CCAP-923](https://codeforamerica.atlassian.net/browse/CCAP-923)
[CCAP-924](https://codeforamerica.atlassian.net/browse/CCAP-924)
- Skips certain screens when the enableMultipleProviders flag is on
- Adds tests to confirm screens are skipped
[CCAP-923]: https://codeforamerica.atlassian.net/browse/CCAP-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCAP-924]: https://codeforamerica.atlassian.net/browse/CCAP-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-923], [CCAP-924] Skip screens when multiple providers flag is on

---

src/main/java/org/ilgcc/app/data/ProviderRepository.java
src/main/java/org/ilgcc/app/data/ProviderRepositoryService.java
src/main/java/org/ilgcc/app/data/importer/ImporterUtils.java
src/main/java/org/ilgcc/app/data/importer/ProviderImporter.java
src/main/resources/db/migration/V2025.05.13.10.12__Update_providers_add_fein.sql

https://codeforamerica.atlassian.net/browse/CCAP-929
Adding FEIN to the providers table, adding method to look up if a FEIN is valid or not.

[CCAP-929] Updating provider importer to support FEINs

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/inputs/InputsConstants.java
src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/actions/ValidateFEIN.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderChoseFEINAsTaxIdType.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/submission/actions/ProviderChoseFEINAsTaxIdTypeTest.java

https://codeforamerica.atlassian.net/browse/CCAP-920
https://codeforamerica.atlassian.net/browse/CCAP-826
https://codeforamerica.atlassian.net/browse/CCAP-927
This PR really is just implementing CCAP-927, and confirming that it also fixes 920 and 826. 
Existing provider screenshots with the new error handling:
New provider functionality works exactly the same as before!

[CCAP-927][CCAP-920][CCAP-826] Updating FEIN validation everywhere

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties

[CCAP-900] Setting the providers next screen to be activities-parent-intro

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/inputs/InputsConstants.java
src/main/java/org/ilgcc/app/inputs/Providerresponse.java

Zip code regex should allow blank

---

src/main/resources/application-qa.yaml

[CCAP-911] Add sentry configuration for QA

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-parent-type.html
src/main/resources/templates/gcc/contact-providers-confirm-email-address.html
src/main/resources/templates/gcc/contact-providers-confirm-phone-number.html
src/main/resources/templates/gcc/contact-providers-edit-email.html
src/main/resources/templates/gcc/contact-providers-edit-phone-number.html
src/main/resources/templates/gcc/contact-providers-email-address.html
src/main/resources/templates/gcc/contact-providers-email-sent.html
src/main/resources/templates/gcc/contact-providers-phone-number.html
src/main/resources/templates/gcc/contact-providers-share-code.html
src/main/resources/templates/gcc/contact-providers-start.html
src/main/resources/templates/gcc/contact-providers-text.html

https://codeforamerica.atlassian.net/browse/CCAP-950

[CCAP-950] Layout for contact-providers-start

---

.github/workflows/deploy-to-qa.yaml

[CCAP-911] Adding Sentry steps for QA

---

.github/workflows/deploy-to-qa.yaml

[CCAP-911] QA Sentry stuff

---

src/main/resources/application.yaml

Update application.yaml to set dts-integration-enabled's default to false

---

build.gradle

Updating to FFL 1.6.26

---

src/main/java/org/ilgcc/app/submission/actions/SetProvidersAndMaxProvidersWhileRemovingIncompleteIterations.java

https://codeforamerica.atlassian.net/browse/CCAP-992

[CCAP-992] Families with only 1 child should be able to set 3 providers

---

src/main/resources/flows-config.yaml

https://codeforamerica.atlassian.net/browse/CCAP-994

[CCAP-994] Removing unneeded deleteConfirmationScreen

---

src/main/resources/application-qa.yaml

enabling multi providers in qa

---

src/main/resources/application-qa.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml

Reverts codeforamerica/il-gcc-form-flow#1617

Revert "enabling multi providers in qa"

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/children-add.html
src/test/java/org/ilgcc/app/journeys/AddFamilyMembersJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-648
Some screen shots, design is in the ticket.

[CCAP-648] Possible to submit an application without any children who need care

---

build.gradle

Updating FFL to 1.6.32

---

src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java

[CCAP-1040] Adding journey test to ensure looping over provider contacts doesn't break

---

sample.env
src/main/resources/application-dev.yaml

https://codeforamerica.atlassian.net/browse/CCAP-1047

[CCAP-1047] Allowing devs to disable ssl

---

src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java

[ccap-1046](https://codeforamerica.atlassian.net/browse/CCAP-1046)
- moves ccap start date get or default to correct location

[CCAP-1046] - accounts for the fact that ccapstart date can be null

---

src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java

Adds email helper methods

---

src/main/java/org/ilgcc/app/data/importer/FakeResourceOrganizationAndCountyData.java
src/main/java/org/ilgcc/app/submission/conditions/BasicCondition.java

Github / CodeQL wants us to handle these two warnings

---

src/main/java/org/ilgcc/app/data/SubmissionSenderService.java
src/main/resources/templates/fragments/datadogRum.html
src/main/resources/templates/fragments/doc-upload-head.html
src/main/resources/templates/fragments/head.html

https://codeforamerica.atlassian.net/browse/CCAP-1069

[CCAP-1069] Handle unset Datadog environment variables

---

src/main/java/org/ilgcc/app/data/SubmissionSenderService.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/templates/providerresponse/submit-response.html

https://codeforamerica.atlassian.net/browse/CCAP-978

[CCAP-978] Send a multiple provider application to CCMS

---

src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java

Fixing the formatting of SubmissionUtitilies

---

src/main/java/org/ilgcc/app/email/SendProviderDeclinesCareFamilyConfirmationEmail.java
src/main/java/org/ilgcc/app/email/templates/ProviderDeclinesCareFamilyConfirmationEmailTemplate.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/email/SendProviderDeclinesCareFamilyConfirmationEmailTest.java

[CCAP-1002](https://codeforamerica.atlassian.net/browse/CCAP-1002)
- Implements provider declines care
- Adds tests for no providerType, Individual, Program Name
[CCAP-1002]: https://codeforamerica.atlassian.net/browse/CCAP-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-1002] -  email family when provider declines care

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/jobs/ProviderResponseRecurringJob.java

[CCAP-978] Include all providers files in transaction payload

---

src/main/java/org/ilgcc/app/email/SendNewProviderAgreesToCareFamilyConfirmationEmail.java
src/main/java/org/ilgcc/app/email/templates/NewProviderAgreesToCareFamilyConfirmationEmailTemplate.java
src/main/java/org/ilgcc/app/email/templates/ProviderAgreesToCareFamilyConfirmationEmailTemplate.java
src/main/java/org/ilgcc/app/email/templates/ProviderDidNotRespondToFamilyEmailTemplate.java
src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/email/SendNewProviderAgreesToCareFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendProviderAgreesToCareFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendProviderDidNotRespondToFamilyEmailTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

[CCAP-1001] Update NewProviderAgreesToCareFamilyConfirmationEmailTemplate

---

src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
src/main/java/org/ilgcc/app/pdf/helpers/ProviderApplicationPreparerHelper.java

[CCAP-975] - map multiple providers follow up

---

src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderIsRegistering.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_MultipleProvider.java
src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_SingleProvider.java

https://codeforamerica.atlassian.net/browse/CCAP-1096

[CCAP-1096] Cleaning up providerPaidCcap logic

---

build.gradle

Reverts codeforamerica/il-gcc-form-flow#1711

Revert "Bump org.jobrunr:jobrunr-spring-boot-3-starter from 7.5.3 to 8.0.0"

---

src/main/java/org/ilgcc/app/RobotsController.java
src/main/java/org/ilgcc/app/utils/CanonicalUrlService.java
src/main/java/org/ilgcc/app/utils/ScreenControllerAdvice.java
src/main/resources/application-dev.yaml
src/main/resources/application-production.yaml
src/main/resources/application-qa.yaml
src/main/resources/application-staging.yaml
src/main/resources/templates/fragments/head.html
src/test/resources/application-test.yaml

CCAP-933
- Adds controller to serve robots.txt file with proper indexing per environment.
- Adds proper canonical URL per environment. 
- Adds metadata and JSON-LD tags.

[CCAP-933] Add site search indexing and metadata

---

src/main/java/org/ilgcc/app/data/TransactionRepository.java
src/main/java/org/ilgcc/app/data/TransmissionRepository.java
src/test/java/org/ilgcc/jobs/ProviderResponseRecurringJobTest.java

[CCAP-1098] Cleaning up queries

---

src/main/resources/messages.properties

https://codeforamerica.atlassian.net/browse/CCAP-1054?
[CCAP-1054] Update copy for submit-confirmation.general.call-text
[CCAP-1054]: https://codeforamerica.atlassian.net/browse/CCAP-1054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-1054] Update copy for submit-confirmation.general.call-text

---

build.gradle
src/main/resources/application-dev.yaml
src/main/resources/application.yaml
src/test/resources/application-test.yaml

downgrading jobrunr to 7.5.3

---

src/main/java/org/ilgcc/jobs/SendRecurringEmailJob.java

Daily email job should also take the enable email flag into consideration

---

src/main/java/org/ilgcc/app/email/ILGCCEmail.java
src/main/java/org/ilgcc/app/email/ILGCCEmailTemplate.java
src/main/java/org/ilgcc/app/email/SendEmail.java

[CCAP-1180] Making other objects thread safe in the email chain

---

src/main/java/org/ilgcc/app/email/sendgrid/SendGridClientFactory.java
src/main/java/org/ilgcc/app/email/sendgrid/SendGridEmailService.java
src/main/java/org/ilgcc/app/email/sendgrid/SendGridEmailValidationService.java
src/main/java/org/ilgcc/app/email/sendgrid/SendGridValidationResponseBody.java
src/main/java/org/ilgcc/app/email/sendgrid/SendGridWebhookController.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderEmail.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderEmailWhenInputIsPresent.java
src/main/java/org/ilgcc/jobs/SendEmailJob.java
src/main/java/org/ilgcc/jobs/SendRecurringEmailJob.java
src/test/java/org/ilgcc/app/email/sendgrid/SendGridEmailValidationServiceTest.java
src/test/java/org/ilgcc/app/email/sendgrid/SendGridValidationResponseBodyTest.java
src/test/java/org/ilgcc/app/submission/actions/ValidateProviderEmailTest.java
src/test/java/org/ilgcc/app/submission/actions/ValidateProviderEmailWhenInputIsPresentTest.java
src/test/java/org/ilgcc/app/utils/SendGridValidationResponseBodyBuilder.java

[CCAP-1180] Creating a custom client class for the Sendgrid email service, moving to a new package

---

src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java

https://codeforamerica.atlassian.net/browse/CCAP-1004
This email should be sent regardless of whether or not all providers responded. We missed that even though we knew this code would work for all use cases. This just removes the `if` and cleans up some logging.

[CCAP-1004] Family submission successfully transmitted to CCMS email should go for all submissions

---

src/main/resources/templates/providerresponse/provider-id-fein.html

(https://codeforamerica.atlassian.net/browse/CCAP-1168)
Changed button copy on providerresponse/provider-id-fein , changed it from 'submit' to 'continue'.

[CCAP-1168]- Changed button copy on providerresponse/provider-id-fein , changed it from 'submit' to 'continue'.

---

src/main/java/org/ilgcc/app/data/SubmissionSenderService.java
src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
src/main/java/org/ilgcc/app/submission/actions/GenerateDummyFamilySubmissionForDev.java
src/main/java/org/ilgcc/app/submission/actions/SendProviderRegistrationAndFamilyPayloadToCCMS.java
src/main/java/org/ilgcc/app/submission/actions/SetProviderSubmissionStatusAndConnectApplications.java
src/test/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMSTest.java

CCAP-1148
- Fixes PDF mappings, sending to CCMS, and sending emails when family submission has multi-provider off and provider response has multi-provider on

[CCAP-1148] Fix issues with single provider family submission and multi-provider provider response

---

src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
src/main/java/org/ilgcc/app/pdf/helpers/FamilyIntendedProviderPreparerHelper.java
src/main/java/org/ilgcc/app/submission/actions/GenerateShortLinkAndStoreProviderApplicationStatus.java
src/main/java/org/ilgcc/app/submission/conditions/CurrentProviderHasResponded.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/java/org/ilgcc/jobs/ProviderResponseRecurringJob.java
src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmailTest.java
src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_MultipleProvider.java

[CCAP-1090](https://codeforamerica.atlassian.net/browse/CCAP-1090) - Make sure no Provider Selected and No Provider Response is correctly mapped in multi provider.
- Stores provider response status in the provider object
- Updates all field names so that they match
- Updates tests to confirm that data is mapped properly
- Tested locally as well
[CCAP-1090]: https://codeforamerica.atlassian.net/browse/CCAP-1090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-1090], [CCAP-1153] - Make sure no provider and no provider response is working

---

src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java

[CCAP-1090] Fixing tests by handling provider response status not being set

---

src/main/java/org/ilgcc/app/pdf/ApplicationPreparer.java
src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
src/main/resources/pdf-map.yaml
src/test/java/org/ilgcc/app/pdf/ApplicationPreparerTest.java

[CCAP-1213] - makes sure all signatures are in Central time

---

src/main/java/org/ilgcc/jobs/ProviderResponseRecurringJob.java

[CCAP-986] Removing duplicate call

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java

Enhancing generateSubmissionTransactionPayload logging

---

src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java

https://codeforamerica.atlassian.net/browse/CCAP-1238
Upping the number of retries from 3 to 5 for CCMS jobs

[CCAP-1238] Updating CCMS retries from 3 to 5

---

src/main/resources/application-qa.yaml

Default AWS creds to blank in QA

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java

Removing double error logging for CCMS calls

---

build.gradle

Rolling back jobrunr

---

sample.env
src/main/java/org/ilgcc/app/data/importer/FakeResourceOrganizationAndCountyData.java
src/test/java/org/ilgcc/app/submission/actions/SetOrganizationIdAndCCRRNameTest.java

[CCAP-1242](https://codeforamerica.atlassian.net/browse/CCAP-1242)
- Updates sample.env to show future setup in qa, staging and prod (eventually)
[CCAP-1242]: https://codeforamerica.atlassian.net/browse/CCAP-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-1242] - enable cohort 2

---

src/main/java/org/ilgcc/app/email/templates/FamilyApplicationTransmittedConfirmationEmailTemplate.java

https://codeforamerica.atlassian.net/browse/CCAP-1304

[CCAP-1304] Handle selenium putting a null into the json

---

src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java

https://codeforamerica.atlassian.net/browse/CCAP-1303
If a provider hasn't respond, we are still trying to send an email after a successful CCMS transmission. Don't do that.

[CCAP-1303] Only send provider CCMS email if a provider has actually responded

---

src/main/resources/static/assets/css/custom.css

[CCAP-1245 comment](https://codeforamerica.atlassian.net/browse/CCAP-1245?focusedCommentId=20419)
Remove the arrows to the right of a numeric field that allow for increments and decrements

[CCAP-1245] - removes default html 5 behavior of inc or dec numbers

---

src/main/resources/templates/gcc/children-ccap-child-other-ed.html

🔗 Jira ticket
Add icon to children-ccap-child-other-ed page
✍️ Description
[CCAP-1261] Add icon to children-ccap-child-other-ed page
[CCAP-1261]: https://codeforamerica.atlassian.net/browse/CCAP-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-1261] Add icon to children-ccap-child-other-ed page

---

src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java

https://codeforamerica.atlassian.net/browse/CCAP-1336

[CCAP-1336] Adding some logging to CCMSSubmissionPayloadTransactionJob

---

build.gradle
src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java

https://codeforamerica.atlassian.net/browse/CCAP-1259
Actual fix is in FFL: https://github.com/codeforamerica/form-flow/pull/850

[CCAP-1259] Update FFL version to fix PDF stamper issue

---

src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedConfirmationEmailTest.java

Fixing broken test

---

src/main/resources/db/migration/V2025.08.28.1301__add_updated_at_triggers.sql

[CCAP-1229] Adding triggers for the updated_at

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/doc-upload-recommended-docs.html
src/test/java/org/ilgcc/app/journeys/DocumentUploadConditionalLogicJourneyTest.java

🔗 Jira ticket
https://codeforamerica.atlassian.net/browse/CCAP-768?
Update the descriptions for document types on upload-recommended-docs page
📷 Design reference
Updated document type descriptions on the upload-recommended-docs page to match official IDHS guidance. 
- Clarified instructions for working parents, self-employment, school/training, TANF work training, and homelessness.
- Added direct links to official PDF forms where applicable.

[CCAP-768] Update the descriptions for document types on upload-recommended-docs page

---

sample.env

Wanted to clean up sample.env a bit to make it easier to follow and understand for initial set up

Clean up and reorganize sample.env to reflect app context

---

sample.env
src/main/java/org/ilgcc/app/config/CCMSApiConfiguration.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/main/resources/application.yaml

CCAP-1286
Creates a feature flag to toggle on and off the CCMS Api V2. 
**Shows correct log when set to off false**
**Shows correct log when set of true**
**Still hits CCMS and gets a response when false**

[CCAP-1286] Add feature flag to toggle CCMS API version

---

build.gradle
src/main/resources/application-dev.yaml
src/main/resources/application.yaml
src/test/resources/application-test.yaml

https://codeforamerica.atlassian.net/browse/CCAP-1275
This is all we need to do, most likely. But, we need to deploy this as a branch to Staging and get it to break, so we can recreate the error when things deserialize... and then clean up the database and confirm that fixes things. I am unable to recreate the issues locally, unfortunately.

[CCAP-1275] Upgrading to Jobrunr 8.0.2

---

.github/il-gcc-selenium-tests.side

[CCAP-1387] - adding only one passing test

---

src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
src/main/java/org/ilgcc/app/data/UserFileTransaction.java
src/main/java/org/ilgcc/app/data/UserFileTransactionRepository.java
src/main/java/org/ilgcc/app/data/UserFileTransactionRepositoryService.java
src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/app/data/ccms/TransactionFile.java
src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
src/main/java/org/ilgcc/app/utils/enums/TransactionStatus.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/main/resources/db/migration/V2025.09.16.11.25.47__Create_UserFileTransaction.sql
src/test/java/org/ilgcc/CcmsTestConfig.java
src/test/java/org/ilgcc/app/data/UserFileTransactionRepositoryServiceTest.java
src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java
src/test/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJobTest.java
src/test/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJobTest.java

CCAP-1376
Create user_file_transaction table and related repository

[CCAP-1376] Create user_file_transactions table

---

.github/dependabot.yml

Update dependabot.yml to reenable Jobrunr

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java

https://codeforamerica.atlassian.net/browse/CCAP-1406

[CCAP-1406] Reducing log.error noise by downgrading to a log.warn

---

src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3AndSendToCCMS.java

Cleaning up some logging and comments
