src/main/resources/static/robots.txt

[#186631586](https://www.pivotaltracker.com/story/show/186631586)
- The location of robots.txt needs to [be in the root](https://developer.mozilla.org/en-US/docs/Glossary/Robots.txt), not /assets/robots.txt
- Remove `Allow` crawling of the index page, we don't want any page crawled by bots

Update robots for the specifics of this project

---

src/main/resources/static/assets/css/custom.css
src/main/resources/templates/gcc/onboarding-getting-started.html
src/main/resources/templates/gcc/pilot-offboard.html
src/main/resources/templates/index.html

[#186713028](https://www.pivotaltracker.com/story/show/186713028)
- So that we don't have to define the background every time we make a new screen

Make background grey as default for screens, white for the home page

---

.github/workflows/run-tests.yaml

It's confirmed that we don't need these comments for the tests to run.

Remove comments in run-tests that aren't needed

---

src/main/java/org/ilgcc/app/submission/conditions/NeedsFinancialAssistanceForChild.java
src/main/resources/flows-config.yaml

Follow-up of #39 - The rest of the children screens should be skipped if a client answers "yes" to the question "Do you need financial assistance for their child care?"

Fixing flow logic

---

build.gradle

[#186712950](https://www.pivotaltracker.com/story/show/186712950)
Specify the exact version for dependencies in our `build.gradle` so that Dependabot can manage posting upgrade PR's.
I used this terminal command to get the versions Gradle was using:
```bash
./gradlew dependencies
```

Add exact versions in build.gradle for Dependabot

---

src/main/resources/application-dev.yaml
src/main/resources/application.yaml

Update config so that non-dev environments have an error page instead of showing the stack trace

Only showing stack-trace in dev env 🍖 

---

src/main/java/org/ilgcc/app/utils/GenderOption.java
src/main/resources/templates/fragments/inputs/checkboxFieldset.html
src/main/resources/templates/gcc/children-ccap-info.html

Follow-up of #72 
Added `noneOfTheAboveLabel` param for checkboxFieldsets
```html
<th:block th:replace="~{fragments/inputs/checkboxFieldset ::
checkboxFieldset(inputName='childGender',
label=#{children-ccap-info.gender-question},
options=${genderOptions},
noneOfTheAboveLabel=#{general.inputs.prefer-not-to-answer})}"/>
```

Adding support for "none of the above" in checkboxFieldset

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/children-add.html
src/main/resources/templates/gcc/children-delete.html

[#186822601](https://www.pivotaltracker.com/story/show/186822601)
I wanted to get the subflow delete functionality working. We can update the design once we have it.
- Not following a design, as they're not ready yet
- Taking from [form flow starter app delete confirmation](https://github.com/codeforamerica/form-flow-starter-app/blob/main/src/main/resources/templates/ubi/incomeDeleteConfirmation.html)
- Delete functionality is working

Add child delete confirmation screen (design from ffsa)

---

src/main/java/org/ilgcc/app/submission/actions/SetWeeklyScheduleGroup.java
src/main/resources/flows-config.yaml
src/main/resources/templates/gcc/activities-class-hourly-schedule.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/submission/actions/SetWeeklyScheduleGroupTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

Follow-up of PT#186900938
Adding an action to format the weekly schedule selection from the previous page - this will be shown when the client selects the "hours are the same" checkbox
From Carl
> If they are not continuous in any way, we should just list each day separately.

Formatting grouped weekdays

---

src/main/resources/templates/gcc/children-add.html

Design review follow-up. Buttons should be stacked vertically

Stacking buttons for consistency

---

src/main/java/org/ilgcc/app/GccDevController.java
src/main/resources/templates/fragments/gcc-icons.html

Adding dev-only endpoint for viewing all available icons --> "/gcc-dev/icons"

Refactor Icon fragments

---

src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/gcc/children-ccap-start-date.html

- visually hide helper text
[#186822601](https://www.pivotaltracker.com/story/show/186822601)
Fix design feedback on `children-ccap-start-date`
Feedback:
Result of this PR:
[Figma screen](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190%3A34116&mode=design&t=jFe0OFD0ddpMRllL-1)

Add label to children-start-date

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/actions/FormatParentConfirmationAddress.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/parent-confirm-address.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/utils/Page.java

PT#187108114
Adding "parent-confirm-address" screen with home-address when smarty-streets does not find a suggested address
Follow-up
- Check if mailing address is different than home address and use that instead
- Design for when smarty-streets does find an address

Adding "parent-confirm-address" screen - no address found

---

src/main/java/org/ilgcc/app/submission/conditions/ParentIsExperiencingHomelessness.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/parent-no-permanent-address.html
src/test/java/org/ilgcc/app/journeys/CcapStartDateTest.java
src/test/java/org/ilgcc/app/journeys/ParentAddressTest.java
src/test/java/org/ilgcc/app/utils/AbstractMockMvcTest.java
src/test/java/org/ilgcc/app/utils/FormScreen.java

PT#187108114
Adding navigational "parent-no-permanent-address" page 
Not in this PR:
- Skipping tests for now since they depend on the completion of address screens

Adding "parent-no-permanent-address" page

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/actions/FormatParentConfirmationAddress.java
src/main/java/org/ilgcc/app/submission/conditions/ParentIsExperiencingHomelessness.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/gcc-icons.html
src/main/resources/templates/gcc/parent-mailing-address.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[#187108114](https://www.pivotaltracker.com/story/show/187108114)
* `parent-mailing-address` screen was added.  Mailing address fields are hidden when a users select `Same as home address`.  Values from the home address are copied to the mailing address when `Same as home address` checkbox is selected.  
* Mailing address is validated
* `parent-confirmation-screen-1` is updated to match figma
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190-34036&mode=design&t=FAySXKvBrlW5S7tN-4)

WIP - Create `parent-mailing-address` screen

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/parent-partner-info-service.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[#187108143](https://www.pivotaltracker.com/story/show/187108143)
Adds the `parent-partner-info-service` screen.
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190%3A34083&mode=design&t=4kcRfQUWjGIYWbTT-1)

Add parent-partner-info-service screen

---

src/main/resources/templates/fragments/skip.html
src/main/resources/templates/gcc/parent-partner-info-disability.html

[#187108143](https://www.pivotaltracker.com/story/show/187108143)
Fix [issue from previous PR](https://github.com/codeforamerica/il-gcc-form-flow/pull/125#discussion_r1523866299).
- Remove skip fragment
- Convert skip to button
- Set value to skip to replace potential previous true/false

Fix skip link behavior

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/actions/ValidateAdultDependentBirthdate.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/children-info-basic.html
src/main/resources/templates/gcc/parent-add-adults-detail.html
src/main/resources/templates/gcc/parent-partner-info-basic.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

PT#186901269
- Adding "parent-add-adult-details" page
- Consolidate some duplicate message properties (might be something we integrate back into FFL)
Follow-up
- Delete functionality for parent list
- Mixpanel tracking
- Date helper-text (requires some a11y discussion)
[Figma link](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=1190-41094&mode=design&t=iWKag0lNjgyL8vGi-0)

Adding "parent-add-adult-details" page

---

.github/pull_request_template.md
.github/reviewer-lottery.yml
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/static/assets/css/custom.css

[CCAP-104](https://codeforamerica.atlassian.net/browse/CCAP-104)
- Hide link to "download PDF" if you can't download a PDF (when `href="#"`)
- Clean up GitHub usernames
- Clean up pull request template to say Jira instead of PT
- Test out Jira integration
[CCAP-104]: https://codeforamerica.atlassian.net/browse/CCAP-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ccap 104 fix home page download pdf link

---

sample.env

N/A
Clear `SPRING_PROFILES_ACTIVE` env variable in sample.env. This means that Form Flow will be pulled from Maven instead of being built locally.
N/A
- [N/A] Added relevant tests
- [N/A] Meets acceptance criteria

Clear SPRING_PROFILES_ACTIVE in sample.env

---

src/main/java/org/ilgcc/app/inputs/Gcc.java

[](https://codeforamerica.atlassian.net/browse/CCAP-120)
Parent and Parent Partner phone number validation was based on having a minimum of 9 digits. Now it's based on the Phone number annotation.
Start an application
on page "flow/gcc/parent-contact" 
- leave it blank, confirm you can move forward
- add an incomplete number and confirm you can't move forward
- add 10 digits and confirm you can move forward
Add a partner
on page gcc/parent-partner-contact
- leave it blank, confirm you can move forward
- add an incomplete number and confirm you can't move forward
- add 10 digits and confirm you can move forward

CCAP-120 Fix phone number validation for parent and parent partner

---

src/main/java/org/ilgcc/app/submission/actions/FormatSubmittedAtDate.java
src/main/resources/flows-config.yaml
src/main/resources/templates/fragments/mixpanelTracking.html
src/test/java/org/ilgcc/app/submission/actions/FormatSubmittedAtDateTest.java

[CCAP-41](https://codeforamerica.atlassian.net/browse/CCAP-41)
- Always display submitted at time in the time zone `America/Chicago` (this handles standard and daylight time)
- Add a test to check that GMT shows as CT
[CCAP-41]: https://codeforamerica.atlassian.net/browse/CCAP-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-41 Show submittedAt in Central Time

---

src/main/resources/application.yaml
src/main/resources/templates/fragments/inputs/overrides/fileUploader.html
src/main/resources/templates/gcc/doc-upload-add-files.html

[Jira Ticket](https://codeforamerica.atlassian.net/browse/CCAP-35?atlOrigin=eyJpIjoiMDBjMmIxZDVjN2JkNDU5MjhjYmUxNDVjZTFjM2Y0M2IiLCJwIjoiaiJ9)
Added `fileUploader` fragment to `doc-upload-add-files` screen. We also added Mixpanel tracking to select events 
track cancel clicks with the event name file_upload_cancel and the file_size, file_type, and page_name as properties on that event.

Ccap 35 implement file upload functionality

---

src/main/resources/templates/gcc/submit-complete.html

[CCAP-41](https://codeforamerica.atlassian.net/browse/CCAP-41?focusedCommentId=10367)
On `submit-complete`, hide the email notification text if an email was not given to us.
[CCAP-41]: https://codeforamerica.atlassian.net/browse/CCAP-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-41 Hide email notification text if there is no email

---

src/main/java/org/ilgcc/app/submission/actions/PartnerSetJobWeeklyScheduleGroup.java
src/main/java/org/ilgcc/app/submission/conditions/PartnersWorkDaysOrHoursVaryDoNotVary.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-partner-job-hourly-schedule.html
src/main/resources/templates/gcc/activities-partner-job-weekly-schedule.html
src/main/resources/templates/gcc/activities-partner-next-work-schedule.html
src/main/resources/templates/gcc/activities-partner-work-schedule-vary.html
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

CCAP-27
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?node-id=1322-7833&t=y5u0LwKgTY7D993C-4)

CCAP-27-add-secondary-parents-work-schedule-to-an-application

---

scripts/setup.sh

Two little tweaks to the setup script. 
The first was what I had to do manually before re-running the script. This error was happening with the removed line:
```
mperlman@codeforamerica.org@Marcs-MacBook-Pro-2 ~ % brew tap homebrew/cask-versions
Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```
The second is just because it appears that new MBPs, or at least mine, didn't come with either a .bashrc or .zshrc file. I had to look at the script to figure out what happened, so this will give future folks a heads up!

updating the setup.sh script with the change i needed to make to get it to work

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-partner-add-job.html
src/main/resources/templates/gcc/delete-job.html
src/main/resources/templates/gcc/delete-partner-job.html
src/main/resources/templates/gcc/delete-person.html
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java

CCAP-25
[Figma](https://codeforamerica.atlassian.net/browse/CCAP-25)

Updated copy and added tracking to No, keep it links

---

src/main/resources/messages.properties

https://codeforamerica.atlassian.net/browse/CCAP-119
@MThorpester noticed that the secondary parent string, which was not noted in the original ticket, used the old phrasing. Confirmed with Carl that we want the secondary string to match the primary string.

[CCAP-119] Tweaking the secondary parent string to match the primary

---

src/main/java/org/ilgcc/app/inputs/Gcc.java

https://codeforamerica.atlassian.net/browse/CCAP-229
The spouse inputs for first/last name were using the generic error message, instead of the first/last name specific required messages

[CCAP-229] Fixing error messages to use specific first/last name messaging for spouse

---

.gitignore
README.md
sample.env
scripts/generate_localhost_cert.sh
scripts/setup.sh
src/main/resources/application-dev.yaml

[CCAP-189](https://codeforamerica.atlassian.net/browse/CCAP-189)
This branch allows us to us `https` when developing on `localhost`.
If you already have this repo set up, here he how you'd add https:
* Pull down this PR
* Go to the root of the repo in a terminal
* Run `sh ./scripts/generate_localhost_cert.sh`
* Go into your `.env` file and add the key `KEY_STORE_PASSWORD`
* The value of `KEY_STORE_PASSWORD` is in our shared lastpass folder called `Localhost cert password`
* Start the app locally
* In the browser go to `https://localhost:8080`
* Once you visit `https` at least once in a browser, it should force `http` to `https` moving forward using the header [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security)
* Success! 🎉 …

Add the ability to use a SSL for localhost

---

src/main/resources/templates/gcc/activities-parent-type.html
src/main/resources/templates/gcc/submit-sign-name.html
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
src/test/java/org/ilgcc/app/journeys/SignatureJourneyTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

[Link](https://codeforamerica.atlassian.net/browse/CCAP-154)
- updated activities type logic to only collect activities if the partner is eligible
- updated submission test builder to include "parentHasQualifyingPartner" set to true

Collect parent partner activities only if partner qualifies

---

src/main/resources/application-staging.yaml

Fix staging redirect by simply turning off the jobrunr dashboard.

Disable jobrunr dashboard in staging for now to stop the redirect

---

build.gradle

No Jira ticket, this PR resolves an issue we were seeing with jackson-databind and jackson-core compatibility after a dependabot update.
Updates jackson-databind to the most recent compatible version 2.16.2

Revert jackson-databind to the most recent compatible version

---

src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/submit-complete.html
src/main/resources/templates/gcc/submit-confirmation.html
src/main/resources/templates/gcc/submit-next-steps.html
src/main/resources/templates/gcc/submit-sign-name.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[Link](https://codeforamerica.atlassian.net/browse/CCAP-191)
- Moves application submission to sign-name page
- Changes the lock application configuration to after sign-name

Implement lock app after submit

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/templates/gcc/parent-partner-info-basic.html

[CCAP-186](https://codeforamerica.atlassian.net/browse/CCAP-186)
- Remove `parentPartnerGender` field and question
- I decided to NOT remove the now unused translations. I could go either way, but I figured if we need those translations in the future, better to have them there and in Transifex.
[CCAP-186]: https://codeforamerica.atlassian.net/browse/CCAP-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-186 Remove parentPartnerGender field

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/onboarding-getting-started.html

This ticket adds eligibility information in the onboarding-getting started page, pet Carl's comment: https://codeforamerica.atlassian.net/browse/CCAP-234?focusedCommentId=11042
The strings describing eligible activities have been copied over from the FAQ Screen. These differ from Carl's comment in the Jira Ticket and the design but they are matching what is in FAQ because as Karen confirmed: (1) They should match. (2) the FAQ page has language already reviewed by the IDHS partners: https://cfastaff.slack.com/archives/C0648BQM6UX/p1721685187967209?thread_ts=1721682568.423519&cid=C0648BQM6UX

Update onboarding-getting-started eligibility language

---

src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/templates/gcc/activities-add-jobs.html
src/main/resources/templates/gcc/activities-parent-type.html
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

[Link To Jira Ticket](https://codeforamerica.atlassian.net/browse/CCAP-242)
- if user adds a preferredName, it is prioritized as the name displayed in `activities-parent-type` and `activities-add-jobs`
- if the user adds an empty "    " preferredName, it will be ignored
- if no preferredName exists, the parentFirstName will be used (note that firstName is a required field)

Uses preferred first name for applicant if it exists.

---

src/main/java/org/ilgcc/app/pdf/ApplicationPreparer.java
src/main/resources/flows-config.yaml
src/main/resources/pdf-map.yaml
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ApplicationPreparerTest.java

[CCAP-63](https://codeforamerica.atlassian.net/browse/CCAP-63)
- Add unit test for `parentFullName`
- Add unit test for `receivedTimestamp`
- Ignore these fields in `verifyPDF` because fields from custom preparers aren't in the db and that's a limitation of our pdf testing.
- I moved the call to the action `FormatSubmittedAtDate` to happen on the `submit-confirmation` screen so that it was triggering after the `submittedAt` is filled, [so that the confirmation screen correctly displays the formatted date time](https://cfastaff.slack.com/archives/C0648BQM6UX/p1721834799327459) (this was not apart of the ticket but it was simple and closely releated).
[CCAP-63]: https://codeforamerica.atlassian.net/browse/CCAP-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

CCAP-63 Add new PDF custom preparers

---

src/main/resources/application-production.yaml

We don't need to determine dashboard settings in the production env because the dashboard is disabled by default, and only enabled in a different port in aptible.

Remove dashboard being disabled in prod

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/activities-partner-add-job.html
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-243
Button text on activities-partner-add-jobs screen says “That is all my jobs”, but should read "That is all their jobs"

[CCAP-243] Typo on activities-partner-add-jobs screen

---

src/main/resources/messages.properties
src/test/java/org/ilgcc/app/journeys/ActivitiesJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-267
inconsistent punctuation in card titles - throughout the application, some titles have no punctuation while others have a period at the end

[CCAP-267] Remove periods from the end of H1 titles

---

src/main/java/org/ilgcc/app/GlobalControllerExceptionHandler.java

[CCAP-252](https://codeforamerica.atlassian.net/browse/CCAP-252)
- Handle `IllegalArgumentException`
With this global adviser, when an illegal character is passed to an argument, in this case `lang=../..`, it is handled by redirecting to the `/error` screen, thus handling the exception.
[CCAP-252]: https://codeforamerica.atlassian.net/browse/CCAP-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-252 Handle illegal arguments

---

src/main/resources/templates/fragments/inputs/timeRange.html
src/main/resources/templates/fragments/screens/activities-class-hourly-schedule.html
src/main/resources/templates/gcc/activities-job-hourly-schedule.html
src/main/resources/templates/gcc/activities-partner-job-hourly-schedule.html
src/main/resources/templates/gcc/children-childcare-hourly-schedule.html

[Jira Ticket](https://codeforamerica.atlassian.net/browse/CCAP-257)
- Add ability to add (required) to the timeRange fragment
- Set timeRange to required for all hourly schedules

Implement hourly schedule required tag

---

src/main/resources/static/assets/css/custom.css

[Ticket](https://codeforamerica.atlassian.net/browse/CCAP-297)
- Updated the required input color to one matching honeycrisp
- made a PR in FFL to match the change: https://github.com/codeforamerica/form-flow/pull/587/files

CCAP-297 Set required input same as error message color

---

src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java

https://github.com/codeforamerica/il-gcc-form-flow/pull/new/marc-CCAP-334
Somehow first name is null, which is impossible because it's a required field. So this is probably just someone testing downloading the pdf early in the flow, but let's just handle is nicely and log it so if it does happen again... we can investigate!

[CCAP-334] Handle null first name

---

src/main/resources/static/assets/css/custom.css

[CCAP-262](https://codeforamerica.atlassian.net/browse/CCAP-262)
- Make link hover color have more contrast in the `.main-header` and `.main-footer`
- Ignore the links in the language dropdown as the background is `white`.
[CCAP-262]: https://codeforamerica.atlassian.net/browse/CCAP-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CCAP-262 Make header and footer link hovers contrast accessible

---

src/main/java/org/ilgcc/app/config/AuthenticationConfiguration.java

https://codeforamerica.atlassian.net/browse/CCAP-254
Just turning off the attempt to provide auth that creates an error on startup, since we don't have auth

[CCAP-254] Using generated security password

---

src/main/java/org/ilgcc/app/submission/conditions/HasRecommendedDocumentsToUpload.java
src/main/java/org/ilgcc/app/utils/RecommendedDocumentsUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/templates/gcc/doc-upload-add-files.html
src/main/resources/templates/gcc/doc-upload-recommended-docs.html
src/test/java/org/ilgcc/app/journeys/DocumentUploadConditionalLogicJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ParentPartnerPreparerTest.java
src/test/java/org/ilgcc/app/pdf/ParentPreparerTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java

Ccap 34 document upload conditional logic

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/actions/CheckClientSubmissionForProvider.java
src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
src/main/java/org/ilgcc/app/submission/actions/SaveApplicationId.java
src/main/java/org/ilgcc/app/submission/actions/SaveApplicationIdFromApplicationId.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/inputs/screenWithOneInputAndSkip.html
src/main/resources/templates/fragments/mixpanelTracking.html
src/main/resources/templates/providerresponse/application-id.html
src/main/resources/templates/providerresponse/ccap-registration.html
src/main/resources/templates/providerresponse/response.html
src/main/resources/templates/providerresponse/submit-complete.html
src/test/java/org/ilgcc/app/journeys/ProviderResponseShortLinkJourneyTest.java
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
src/test/java/org/ilgcc/app/utils/TimeOption.java

[CCAP-352](https://codeforamerica.atlassian.net/browse/CCAP-352)
- Continuation of [creating new provider flow](https://github.com/codeforamerica/il-gcc-form-flow/pull/633) and [handling confirmation codes](https://github.com/codeforamerica/il-gcc-form-flow/pull/615)
- Implements CCAP-registration form
- application-id screen which pre-fills the family application code
- implements /response which displays details for the family application
- implements submit-complete with the appropriate details depending on what the provider has decided
- mixpanel analytics on provider decision
--- 
Tests the happy path of the provider flow
Tests the Expired and Active statuses using the short link. 
[Figma Designs here](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences-(W …

[CCAP-352] Allow providers to respond to application

---

src/test/java/org/ilgcc/jobs/PdfTransmissionJobTest.java
src/test/java/org/ilgcc/jobs/SampleJobsTest.java

This fixes an issue where if the main application was running when you ran tests, the jobrunr tests would fail because they would attempt to load the jobrunr dashboard at the same address as the main apps dashboard. 
This fixes the issue by changing the port used in test.

Fixes an issue where jobrunr tests would fail if the app was running

---

src/main/java/org/ilgcc/app/submission/actions/RemoveIncompleteChildIterations.java
src/main/java/org/ilgcc/app/submission/actions/RemoveIncompleteJobIterations.java
src/main/java/org/ilgcc/app/submission/actions/RemoveIncompletePartnerJobIterations.java
src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-396?atlOrigin=eyJpIjoiNGRlZWYyNDA1Y2ZlNGMwNGJmODQ5NDlhYmFkNmNlZGMiLCJwIjoiaiJ9
When a user lands on the review screen for one of the subflows (children, jobs, partner jobs), an action will be triggered that removes any incomplete iterations from said subflow and saves the submission with the updated subflow that no longer includes incomplete iterations.
This should also stop incomplete iterations from being mapped to the PDF since they will no longer be present in the submission.

Remove incomplete iterations from subflows

---

build.gradle
src/main/resources/application-demo.yaml
src/main/resources/application-dev.yaml
src/main/resources/application-staging.yaml
src/main/resources/application.yaml

https://codeforamerica.atlassian.net/browse/CCAP-420
This change will mean that a family submission gets a confirmation code, but the provider response will not. To test this, just go through the flow as a family and look in the DB -- there will be a value in the short_code column of the Submission table. Then respond as a provider -- that Submission entry will have a null short_code still.

[CCAP-420] Updating the project to use new FFL and the modified yaml format

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/gcc-icons.html
src/main/resources/templates/gcc/contact-provider-info.html
src/main/resources/templates/gcc/submit-provider-agreement-handoff.html

CCAP-417
- Implement submit-provider-agreement-handoff screen
- The screen matches the designs
- All content is voiced by the screen reader
- All the interactive elements are navigable using the keyboard
- The submit-provider-agreement-handoff screen is the destination for the “I’d prefer to print and deliver my application in-person.” link on the Contact-provider-info screen
https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences-(WIP)?node-id=1-9189&t=Rw698undoDqscCAV-4

[CCAP-417] Add submit-provider-agreement-handoff screen

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/contact-provider-message.html
src/main/resources/templates/gcc/next-steps-pdf-delivery.html
src/main/resources/templates/gcc/onboarding-confirm-provider.html
src/main/resources/templates/gcc/submit-next-steps.html

CCAP-405
Clients will see different content depending on whether they chose to send their message by email / SMS or by downloading and delivering the PDF themselves when the feature flag is on. They will see a third version of the content when the feature flag is off. 
https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Full-Flow?node-id=2412-10303

CCAP-405 Update next steps screens

---

src/main/resources/templates/fragments/mixpanelTracking.html

CCAP-409
When the provider submits their response on the provider-response/response screen, fire a special event provider_response. That event should contain the unique id for the family application as a property on the event. That event should also contain a property indicating the response, either provider_agreed or provider declined.

[CCAP-409]

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
src/main/java/org/ilgcc/app/submission/actions/GenerateDummyClientSubmissionForDev.java
src/main/java/org/ilgcc/app/submission/actions/RemoveDummySubmissionForDev.java
src/main/java/org/ilgcc/app/submission/actions/SaveApplicationId.java
src/main/java/org/ilgcc/app/submission/actions/ValidateConfirmationCodeAndSaveId.java
src/main/resources/flows-config.yaml
src/main/resources/templates/fragments/inputs/overrides/number.html
src/main/resources/templates/providerresponse/application-id.html
src/main/resources/templates/providerresponse/submit-complete-final.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

This creates a dummy content family submission in the provider response flow if you are in the dev environment. 
This makes it so you don't need to fill out a family submission to get a short code before going through the provider response flow. 
Using this fake filler configuration fake filler will autofill the correct family short code for you on the corresponding page in the provider response flow. 
[fake-filler-2024-11-07.txt](https://github.com/user-attachments/files/17669521/fake-filler-2024-11-07.txt)

Generate a dummy family submission when going through provider flow

---

sample.env
src/main/resources/templates/fragments/head.html

https://codeforamerica.atlassian.net/browse/CCAP-443
Turns on Datadog replays by environment. Will set up these keys in Staging and Prod immediately after PR approval.

[CCAP-443] making it possible to turn on Datadog replays by environment

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/submit-complete.html
src/test/java/org/ilgcc/app/journeys/DocumentUploadConditionalLogicJourneyTest.java
src/test/java/org/ilgcc/app/journeys/FamilyProviderOnboardingScreensTest.java
src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java

CCAP-433
Change the logic of the `submit-complete` screen and to match Figma
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Full-Flow?node-id=11016-30028&t=PQgZayvwiDX0aqQf-4)

[CCAP-433] Adjust logic and flows for submission and document upload screens

---

src/main/resources/templates/fragments/doc-upload-head.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/head.html

CCAP-314
- Move all <scripts> from the <head> to the footer. This moves scripts from render blocking, but it makes our tests fail, which I wasn’t able to resolve quickly.
- Use [capo.js](https://rviscomi.github.io/capo.js/) to re-arrange the <head> to be the most optimized

[CCAP-314] Optimize scripts and move them to footer

---

src/main/java/org/ilgcc/app/file_transfer/DocumentTransferRequestService.java
src/main/java/org/ilgcc/app/submission/actions/GenerateDummyClientSubmissionForDev.java
src/main/java/org/ilgcc/app/submission/actions/UploadProviderSubmissionToS3.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/providerresponse/info.html
src/main/resources/templates/providerresponse/service-address.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

- Keeps mapping / inputs the same with some minor changes to allow exporting the PDF before the flow is completed
CCAP-478 and CCAP-479
Splits the info screen into info (first and last name, business name) and address as two seperate screens.

[CCAP-478, CCAP-479] Split info screen to info and address screens

---

src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/inputError.html

Fixes a spacing issue pointed out by Carl:
https://codeforamerica.atlassian.net/browse/CCAP-478?atlOrigin=eyJpIjoiYjM0NzVmOGE0MDIwNGE1Mjk2NWY5ZGFlMzJjMjM1ZGMiLCJwIjoiaiJ9

Fix error messages so spacing displays correctly

---

src/main/resources/static/assets/css/custom.css
src/main/resources/templates/gcc/contact-provider-message.html

CCAP-346
Hides the text message button on desktop on the contact-provider-message screen in the GCC flow.

[CCAP-346] Hide text button on desktop

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerFlagOnTest.java

CCAP-502
Will not map the provider response field on page 14 of the PDF if you download the PDF in the client flow. This is done by not mapping it unless 3 business days have passed which should be well after the clients session has expired.

[CCAP-502] Do not map no response from provider for family PDF download

---

src/main/resources/templates/gcc/contact-provider-message.html

CCAP-551
Makes it so screen readers read the link as "Copy to clipboard" instead of "Content copy copy to clipboard", especially on JAWS/Edge.

[CCAP-551] Fix screen reader copy link announcement on JAWS and Edge

---

src/main/resources/templates/gcc/contact-provider-message.html

CCAP-501
Updates the copy to clipboard button on the `contact-provider-message` screen so it announces 'Copied to clipboard' on screen reader when clicked.

[CCAP-501] Announce 'Copied to clipboard' on screen reader when button is clicked

---

src/main/java/org/ilgcc/app/submission/actions/SetProviderType.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderSsnRequired.java
src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/submission/actions/SetProviderTypeTest.java

[CCAP-465](https://codeforamerica.atlassian.net/browse/CCAP-465)
Part 2: Combining the Provider Type concept with display logic to make sure that only providers who are part of the list, see the ssn screen
[CCAP-465]: https://codeforamerica.atlassian.net/browse/CCAP-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-465] - conditionally display provider ssn based on provider type

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/pdf/ProviderSSNPreparer.java
src/main/java/org/ilgcc/app/submission/actions/ValidateTaxIdSSN.java
src/main/java/org/ilgcc/app/submission/conditions/NeedsSSNForTaxID.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/pdf-map.yaml
src/main/resources/templates/providerresponse/registration-tax-id-ssn.html
src/test/java/org/ilgcc/app/pdf/ProviderSSNPreparerTest.java
src/test/java/org/ilgcc/app/submission/actions/NeedSSNForTaxIdTest.java

CCAP-468
- `registration-tax-id-ssn` was added to `providerresponse` flow.  
- `registration-tax-id-ssn` screen is only reached if `SSN` is selected as the `providerTaxIdType` and `providerIdentyCheckSSN` is not present
- `PROVIDER_SSN` has either `providerIdentityCheckSSN` or `providerTaxIdSSN` written to it
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=1487-6539&t=4uzbbS6PeBtH4Ums-4)
[Content Manager](https://docs.google.com/document/d/1ERZ8oqKu_K1HCdm8wQMgCDyYJR-3xF8-d8t7LK84Hmo/edit?tab=t.0#bookmark=id.whtp67m5445e)

Ccap 468 create providerresponse registration tax id ssn screen

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/resources/messages.properties
src/main/resources/templates/fragments/cardHeader.html
src/main/resources/templates/fragments/requiredCardHeader.html
src/main/resources/templates/gcc/activities-parent-type.html

https://codeforamerica.atlassian.net/browse/CCAP-539
This was easy to fix for the error messages themselves, but the header -- since this is not a single input field -- needed a new fragment.

[CCAP-539] Adding error messages for parent and partner activities

---

src/main/java/org/ilgcc/app/pdf/ProviderLanguagesPreparer.java
src/test/java/org/ilgcc/app/pdf/ProviderLanguagePreparerTest.java

CCAP-631
- Any provider language text written into the Other checkbox should be added to the pdf.

[CCAP-470] Writes User Input into Other Detail fields

---

src/main/java/org/ilgcc/jobs/TransmissionsRecurringJob.java

https://codeforamerica.atlassian.net/browse/CCAP-635
In Staging and Demo, so far not in Production, there seems to be a scenario where you can start a provider response, agree to care, and then not have a submitted_at date. This causes the PDF to never transmit -- but if the provider never ever submits their response, we should treat it as such and send the PDF as a no provider response.

[CCAP-635] Fixing small logic flaw in TransmissionsRecurringJob

---

src/main/resources/messages.properties
src/main/resources/templates/index.html

[CCAP-513] - Updates home page notice and updates mixpanel data id

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/faq.html

[CCAP-563] Add questions about being a child care provider to FAQ

---

src/main/java/org/ilgcc/app/utils/CountyOption.java
src/main/java/org/ilgcc/app/utils/CountyOptionUtils.java
src/main/resources/templates/gcc/onboarding-county.html
src/test/java/org/ilgcc/app/submission/actions/CountyUtilTest.java

[CCAP-509] adding additional counties behind enableSDA15Providers flag

---

gradlew

[CCAP-629] Bumping up the heap size

---

build.gradle
src/main/java/org/ilgcc/jobs/EnqueueDocumentTransfer.java

https://codeforamerica.atlassian.net/browse/CCAP-659
If file conversion is turned on, this will on grab files that are PDFs... so any original supporting doc that was a PDF and any converted file. 
If file conversion is turned off, this grabs all the files like it used to... but just alphabetically to be more consistent. (Just a nice little enhancement as long as I was in the code, no overall change really)

[CCAP-659] Storing and transferring converted files

---

src/main/java/org/ilgcc/app/ProviderLinkController.java
src/main/java/org/ilgcc/app/StaticPageController.java
src/main/resources/messages.properties
src/main/resources/templates/error-invalid-code.html
src/main/resources/templates/fragments/gcc-icons.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

[CCAP-661](https://codeforamerica.atlassian.net/browse/CCAP-661)
- Reroutes to incorrect confirmation code screen if confirmation code incorrect
- Keeps current functionality if confirmation code is an empty string or null
[CCAP-661]: https://codeforamerica.atlassian.net/browse/CCAP-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-661] - handle incorrect confirmation code

---

build.gradle
src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/gcc/doc-upload-add-files.html
src/main/resources/templates/providerresponse/mailing-address.html
src/main/resources/templates/providerresponse/provider-number.html
src/main/resources/templates/providerresponse/registration-checks-trainings-notice.html
src/main/resources/templates/providerresponse/registration-doc-upload-add-files.html
src/main/resources/templates/providerresponse/registration-tax-id.html
src/main/resources/templates/providerresponse/response.html
src/main/resources/templates/providerresponse/submit-start.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java

[CCAP-476](https://codeforamerica.atlassian.net/browse/CCAP-476)
- Implements design changes to the response screen
- Upgrades library to 1.6.20 to include updates to reveal component which allow the screen to load open or closed
- Changes the forceShowContent to false in most components so that they correctly load closed
Tests from the heroku branch
[CCAP-476]: https://codeforamerica.atlassian.net/browse/CCAP-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-476] - update design response screen

---

src/main/java/org/ilgcc/app/email/ILGCCEmail.java
src/main/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmail.java
src/main/resources/application-dev.yaml
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/test/java/org/ilgcc/app/submission/actions/SendFamilyConfirmationEmailTest.java

[CCAP-495]
[Content Manager](https://docs.google.com/document/d/1vwtwI1-GcqrGDGf3l1UEk161ahoGqVlCAX0BhmoYnlY/edit?tab=t.0#bookmark=id.douf4myo1zo8)
[CCAP-495]: https://codeforamerica.atlassian.net/browse/CCAP-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-495] Send confirmation email to family with no provider

---

src/main/java/org/ilgcc/app/submission/conditions/EnableProviderMessagingFlagOn.java
src/main/resources/application.yaml
src/main/resources/flows-config.yaml
src/main/resources/templates/gcc/parent-confirm-provider-number.html
src/main/resources/templates/gcc/submit-confirm-provider-email.html
src/main/resources/templates/gcc/submit-confirmation.html
src/main/resources/templates/gcc/submit-contact-method.html
src/main/resources/templates/gcc/submit-contact-provider-email-confirmation.html
src/main/resources/templates/gcc/submit-contact-provider-email.html
src/main/resources/templates/gcc/submit-contact-provider-text-confirmation.html
src/main/resources/templates/gcc/submit-contact-provider-text.html
src/main/resources/templates/gcc/submit-provider-info-edit.html

[CCAP-722](https://codeforamerica.atlassian.net/browse/CCAP-722)
- Creates new feature flag and sets it in heroku (true) , aptible - staging (true), production (false)
- scaffolds screens: 
- submit-contact-method
- submit-contact-provider-email
- submit-confirm-provider-email
- submit-provider-info-edit
- submit-contact-provider-email-confirmation
- submit-contact-provider-text
- parent-confirm-provider-number
- submit-contact-provider-text-confirmation
- submit-confirmation
Displays conditions above when feature flag is on.
[CCAP-722]: https://codeforamerica.atlassian.net/browse/CCAP-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-722] - add new provider messaging flag and scaffold screens

---

src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/screens/child-care-provider-info.html
src/main/resources/templates/gcc/onboarding-provider-info.html
src/main/resources/templates/gcc/submit-edit-provider-email.html
src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java

Since we are basically editing the data from the onboarding-provider-info, I moved the main content into a screen fragment to be reused by onboarding-provider-info and submit-edit-provider-email screen
- submit-edit-provider-email screen loads name, email, phone number if they exist
- submit-edit-provider-email updates only email if it is updated
- submit-edit-provider-email name and phone number fields are disabled
- [ x] Added relevant tests
- [ x] Meets acceptance criteria

[CCAP-739] - submit-edit-provider-email screen

---

src/main/java/org/ilgcc/app/submission/conditions/DisplaySubmitContactProviderEmailScreen.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/submit-contact-provider-email.html
src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java
src/test/java/org/ilgcc/app/submission/actions/DisplaySubmitContactProviderEmailScreenTest.java

[CCAP-733](https://codeforamerica.atlassian.net/browse/CCAP-733)
- Display submit-contract-provider-email when email is selected, and familyIntendedEmail is blank
[CCAP-733]: https://codeforamerica.atlassian.net/browse/CCAP-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-733] - submit contact provider email

---

src/main/resources/application.yaml
src/main/resources/messages.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/gcc/submit-contact-provider-text-confirmation.html
src/test/java/org/ilgcc/app/journeys/GccProviderMessagingFlowJourneyTest.java

[CCAP-740]
```
Message content:
Hi! I applied for CCAP with you as my provider.
Confirmation code: KOSGEB
Please complete your part within 3 business days https://getchildcareil.org/s/KOSGEB 
```
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=17162-40959&m=dev)
Design
PR
[CCAP-740]: https://codeforamerica.atlassian.net/browse/CCAP-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-740] create new submit-contact-provider-text-confirmation screen

---

src/main/java/org/ilgcc/app/email/ILGCCEmail.java
src/main/java/org/ilgcc/app/email/SendAutomatedProviderOutreachEmail.java
src/main/java/org/ilgcc/app/email/SendProviderConfirmationEmail.java
src/main/java/org/ilgcc/app/email/templates/AutomatedProviderOutreachEmailTemplate.java
src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/actions/SendAutomatedProviderEmail.java
src/main/java/org/ilgcc/app/submission/actions/SendAutomatedProviderEmailAndFormatSubmittedAtDate.java
src/main/java/org/ilgcc/app/submission/conditions/hasConfirmedProviderEmail.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/submit-confirm-provider-email.html
src/main/resources/templates/gcc/submit-contact-provider-email-confirmation.html
src/test/java/org/ilgcc/app/email/SendAutomatedProviderOutreachEmailTest.java

[CCAP-727](https://codeforamerica.atlassian.net/browse/CCAP-727)
The provider notification email should be sent immediately
- The reply to address for the email should be [noreply@getchildcareil.org](mailto:contact@getchildcareil.org)
- The sender address for the email should be [noreply@getchildcareil.org](mailto:noreply@getchildcareil.org)
- The sender name for the email should be Child Care Assistance Program Applications - Code for America on behalf of Illinois Department of Human Services
- The footer of the email must clearly identify Code for America as the sender and the address
[CCAP-727]: https://codeforamerica.atlassian.net/browse/CCAP-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-727] - Send automatic email notification to provider

---

src/main/java/org/ilgcc/app/ProviderLinkController.java

https://codeforamerica.atlassian.net/browse/CCAP-701
Pretty straight forward and we're just removing the old longer path for confirmation codes. Also, changed the log.error to log.debug, because it's not actually an error if we can't find a submission for a given code-- it could just be gibberish from a person trying to see what happens.

[CCAP-701] Clean up code for handling links to the provider response

---

src/main/java/org/ilgcc/jobs/PdfTransmissionJob.java
src/test/java/org/ilgcc/jobs/PdfTransmissionJobTest.java

https://codeforamerica.atlassian.net/browse/CCAP-802
The Jobrunr job to upload an application PDF to DTS was not regenerating the presigned Url on retries. That meant if the first few retries failed, the exponential backoff would result in a url that was expired. The job to upload supporting documents takes the UserFile itself and thus can regenerate the supporting document presigned url. 
This is confirmed by the fact that requeuing the supporting documents jobs that failed all succeed hours later, but the application submission jobs won't succeed.

[CCAP-802] DTS job regenerates presignedUrl each time the job runs

---

src/main/java/org/ilgcc/app/email/ILGCCEmail.java
src/main/java/org/ilgcc/app/email/SendUnidentifiedProviderConfirmationEmail.java
src/main/java/org/ilgcc/app/email/templates/UnidentifiedProviderConfirmationEmailTemplate.java
src/main/java/org/ilgcc/app/submission/actions/SendUnidentifiedProviderAndFamilyConfirmationEmails.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/email/DailyNewApplicationsProviderEmailTemplateTest.java
src/test/java/org/ilgcc/app/email/SendFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendFamilyConfirmationNoProviderEmailTest.java
src/test/java/org/ilgcc/app/email/SendNewProviderAgreesToCareFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendProviderAgreesToCareFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendProviderConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendProviderDeclinesCareFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendProviderDidNotRespondToFamilyEmailTest.java
src/test/java/org/ilgcc/app/email/SendUnidentifiedProviderConfirmationEmailTest.java

https://codeforamerica.atlassian.net/browse/CCAP-817
https://codeforamerica.atlassian.net/browse/CCAP-818
Family email is actually the same email as the No Provider Response email per the ticket/talking with Carl. Because this email is traditionally sent from the No Provider Response job, we need to explicitly load the Family submission object based on the provider submission.
Provider email is a new email itself.
PR contains tests, plus refactoring/cleanup of all the other email tests!

[CCAP-817][CCAP-818] New emails for family and provider when provider is unidentified

---

src/main/resources/messages.properties
src/main/resources/templates/providerresponse/provider-number.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderResponseWithFEINJourneyTest.java

[CCAP-812]
Steps
1.  Examine page to see best process for modifying provider number
2.  Add new message-properties values for the screen
3.  Add skip location input triggered by fein flag.  
4.  Add skip text for `singlescreenwithoneinputandaskip`
5.  Add test for screen when fein flag is on.  check of link to fein scerren is displayed. 
6. Check that acceptance criteria have been met
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=5593-34586&m=dev)
[CCAP-812]: https://codeforamerica.atlassian.net/browse/CCAP-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-812] update content of providerresponse provider number screen

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerTest.java

[CCAP-806](https://codeforamerica.atlassian.net/browse/CCAP-806)
- This work doesn’t need to be protected by enableProviderResponseFein feature flag created in https://codeforamerica.atlassian.net/browse/CCAP-809, but that flag should not be enabled on production until this work is deployed.
- When a provider submits a response without providing either a valid CCMS id number or FEIN, provider response is mapped as "Unable to identify provider - no response to care arrangement"
-- These fields are also mapped
providerResponseFirstName
providerResponseLastName
providerResponseBusinessName
providerResponseServiceStreetAddress1
providerResponseServiceStreetAddress2
providerResponseServiceCity
providerResponseServiceState
providerResponseServiceZipCode
providerMailingStreetAddress1 …

[CCAP-806] - missing provider id and fein for provider response

---

src/main/java/org/ilgcc/app/pdf/ProviderApplicationPreparer.java
src/test/java/org/ilgcc/app/pdf/ProviderApplicationPreparerTest.java

[CCAP-807](https://codeforamerica.atlassian.net/browse/CCAP-807)
- Updates provider logic to set providerResponse as "Provider declined"
- Maps:
providerResponseFirstName
providerResponseLastName
providerResponseBusinessName
providerResponseServiceStreetAddress1
providerResponseServiceStreetAddress2
providerResponseServiceCity
providerResponseServiceState
providerResponseServiceZipCode
providerMailingStreetAddress1
providerMailingStreetAddress2
providerMailingCity
providerMailingState
providerMailingZipCode
providerResponseContactEmail
providerResponseContactPhoneNumber
[CCAP-807]: https://codeforamerica.atlassian.net/browse/CCAP-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-807] - Update mapping when existing provider declines care

---

src/main/java/org/ilgcc/app/data/CCMSDataService.java
src/main/java/org/ilgcc/app/data/CCMSDataServiceImpl.java
src/main/java/org/ilgcc/app/data/ResourceOrganizationRepository.java
src/main/java/org/ilgcc/app/data/importer/FakeProviderDataImporter.java
src/main/java/org/ilgcc/app/submission/router/ApplicationRoutingServiceImpl.java
src/test/java/org/ilgcc/app/data/ProviderAndSiteAdministeredResourceOrganizationTest.java
src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java
src/test/java/org/ilgcc/app/submission/actions/SetResourceOrganizationTest.java

[CCAP-715](https://codeforamerica.atlassian.net/browse/CCAP-715)
- Creates a new query that looks for site administered providers in a given set of SDAs
- Creates a method that determines active SDAs based on active caseload codes (active + pending if feature flag is on) set in our ENV
- Limits emails to only site administered SDAs that are active (Out of scope but relevant)
- Updates provider faker to be more human readable
- Updates set Resource organization test
* When a provider responds to an application with a provider id number that is associated with a site administered provider as the processing organization in SDA 2, SDA 6. or SDA 15, then that application should be routed to that site administered provider in CCMS for processing
* When a provider responds to an application with …

[CCAP-715] - limit site administered site routing to active sdas

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/submission/conditions/HasFEIN.java
src/main/java/org/ilgcc/app/submission/conditions/HasFEINOrEIN.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/providerresponse/fein.html
src/main/resources/templates/providerresponse/paid-by-ccap.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderResponseWithFEINJourneyTest.java

[CCAP-813]
Steps to Complete:
1. Check Fein Screen against figma designs and the content manager
2. Add Fein text to message properties
3. Add icons to match figma
4. Properly link Yes and I'm not sure links to their proper screens
5. Add Journey test to ensure navigation when user selects yes/no or i'm not sure
[Figma](https://www.figma.com/design/lGFsTvWwHoOOJ9XQGPFNmu/IL-CCAP-Provider-Experiences?node-id=5593-34525&t=NLwxxYO4buIgWY3b-4)
[CCAP-813]: https://codeforamerica.atlassian.net/browse/CCAP-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-813] create new providerresponse fein screen

---

src/main/resources/flows-config.yaml

https://codeforamerica.atlassian.net/browse/CCAP-861
There is a bug that if ALLOW_PROVIDER_REGISTRATION_FLOW is set to false, you can go to /flow/providerresponse/registration-start and because pages deeper in the registration flow do not check if that flag is set to true or false, you can essentially enter the provider registration flow and submit a response.
This fix will ensure that every screen in that flow, if you enter through /flow/providerresponse/registration-start will skip until the final screen, which will then return you to the valid /submit-start beginning screen instead.

[CCAP-861] Provider Registration flow needs to check if it's enabled all the way through

---

src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/resources/templates/fragments/inputs/itin.html
src/main/resources/templates/providerresponse/registration-home-provider-itin.html
src/main/resources/templates/providerresponse/registration-tax-id-itin.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationWithITINJourneyTest.java

[CCAP-839]
Make sure the ITIN is valid and 9 digits
Steps to completion
1. Analyze the itin story and figure out implementation plan
2. We will generate an input fragment similar to the ssn input fragment
3. We will generate a itin pattern that matches the rules for itin numbers 
4. Add fragment to screens getting itin inputs
[CCAP-839]: https://codeforamerica.atlassian.net/browse/CCAP-839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-839] Update Error Prevention for ITIN Fields

---

src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java

CCAP-892 / CCAP-893
-  when the `ENABLE_MULTIPLE_PROVIDERS` feature flag is on the client can reach the `providers-intro` screen from the `chldren-add` screen.  [figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=18967-47623&m=dev)  
-  When `ENABLE_MULTIPLE_PROVIDERS` is off you are routed to the `activities-parent-intro` screen.  
-  clicking continue sends you to the `after-submit-contact-provider` if EnableProviderMessaging is on, 
-  if EnableProviderMessaging is off you are routed to the `submit-complete` screen

[CCAP-893] Navigation change for acceptance testing

---

src/main/java/org/ilgcc/jobs/JobRetriesFailedFilter.java
src/main/java/org/ilgcc/jobs/ProviderResponseRecurringJob.java

https://codeforamerica.atlassian.net/browse/CCAP-887
https://codeforamerica.atlassian.net/browse/CCAP-888
https://codeforamerica.atlassian.net/browse/CCAP-889
This should handle any/all exceptions that occur within the CCMS job, and surface them with the new `log.error` by enhancing the Datadog monitor:
I also fixed the logging for the No Provider Response job, and adjusted the Datadog monitor there too.

[CCAP-887][CCAP-888][CCAP-889] Alerting and retry logic for CCMS jobs

---

src/main/java/org/ilgcc/app/submission/actions/SendAutomatedProviderEmail.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderEmailWhenInputIsPresent.java
src/main/java/org/ilgcc/app/submission/conditions/DisplayContactProvidersEmailScreen.java
src/main/java/org/ilgcc/app/submission/conditions/HasConfirmedProviderEmail.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/gcc/contact-providers-confirm-email-address.html
src/main/resources/templates/gcc/contact-providers-edit-email.html
src/main/resources/templates/gcc/contact-providers-email-address.html
src/main/resources/templates/gcc/contact-providers-email-sent.html
src/main/resources/templates/gcc/contact-providers-start.html

https://codeforamerica.atlassian.net/browse/CCAP-951
https://codeforamerica.atlassian.net/browse/CCAP-952
CCAP-951:
CCAP-952:
I also updated the prior screen that I made to use the single input style, etc:

[CCAP-951][CCAP-952] Create new contact-providers-email-address, contact-providers-confirm-email-address screens

---

src/main/java/org/ilgcc/app/submission/conditions/HouseholdHasAtLeastOneChildWithoutAProvider.java
src/test/java/org/ilgcc/app/submission/conditions/HouseholdHasAtLeastOneChildWithoutAProviderTest.java

CCAP-961
HouseholdHasAtLeastOneChildWithoutAProvider.java condition fails.  This change fixes the error.

[CCAP-961] Update HouseholdHasAtLeastOneChildWithoutAProvider.java

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/submission/actions/PopulateChildcareSchedulesIteration.java
src/main/java/org/ilgcc/app/submission/conditions/DisplaySchedulesStartCareScreen.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/fragments/inputs/subflowScreenWithOneInput.html
src/main/resources/templates/gcc/schedules-start-care.html
src/main/resources/templates/gcc/schedules-start.html

[CCAP-940]
The schedules-start-care screen exists
**Note**
There are some corrections.  
schedules-start screen was missing the no-provider checkbox.  That is added in this repo
schedules-start-care screen was missing logic to skip the screen when a provider was not selected.  That action has been added.  
- [Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=19449-5211&t=MC1BbY3r9xh0tTqM-4)
- [Content Manager](https://docs.google.com/document/d/1vwtwI1-GcqrGDGf3l1UEk161ahoGqVlCAX0BhmoYnlY/edit?tab=t.0#bookmark=id.ig52mr8xx7dm)
[CCAP-940]: https://codeforamerica.atlassian.net/browse/CCAP-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-940] create new schedules-start-care screen

---

src/main/resources/messages.properties
src/main/resources/templates/gcc/schedules-days.html

CCAP-942
Acceptance criteria
Store the answer to the question in the existing field: childcareWeeklySchedule

[CCAP-942] Add schedules-days.html screen to flow

---

src/main/java/org/ilgcc/app/inputs/Gcc.java
src/main/java/org/ilgcc/app/pdf/helpers/FamilyIntendedProviderPreparerHelper.java
src/main/java/org/ilgcc/app/submission/actions/SetFamilyIntendedProviderName.java
src/main/java/org/ilgcc/app/submission/actions/ValidateProviderName.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderIsCareProgram.java
src/main/java/org/ilgcc/app/submission/conditions/ProviderIsIndividual.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/pdf-map.yaml
src/main/resources/templates/fragments/inputs/overrides/cardHeaderForSingleInputScreen.html
src/main/resources/templates/fragments/inputs/overrides/screenWithOneInput.html
src/main/resources/templates/gcc/providers-add.html
src/main/resources/templates/gcc/providers-location.html
src/main/resources/templates/gcc/providers-name.html
src/main/resources/templates/gcc/providers-type.html
src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccSingleProviderJourneyTest.java
src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_MultipleProvider.java
src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_SingleProvider.java

CCAP-1021
Adds provider type and provider name screens with conditional display logic for inputs on provider-name depending on provider-type selection:
**provider-type:**
**provider-name (individual):**
**provider-name (Care Program):**
**The `provider-info` screen now becomes `provider-location` and the name input is removed.**
[
](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=20371-54603)

[CCAP-1021] Add provider name and type screens - update provider-info to provider-location

---

src/main/resources/templates/gcc/schedules-start.html
src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java

- the available providers.  They can not do both.  
Video of No Provider Checkbox
https://www.loom.com/share/5b690e5183734308aed4e0858f2b693b?sid=481377a0-e7b1-4b20-8fce-394320fa28c9
https://loom.com/i/f504369c427c428fa157640619108f43

[CCAP-939] Fix issues from schedule-start.html

---

src/main/java/org/ilgcc/app/data/SubmissionSenderService.java

https://codeforamerica.atlassian.net/browse/CCAP-932
Most of this ticket was covered by CCAP-1048, but this will add `providerResponseAgreeToCare` back into the family submission's `providers`: 
For example the second provider here:
```
"providers": [
{
"uuid": "0f377eb5-092a-45d6-8e79-64ea89caa13f",
"providerType": "Individual",
"providerLastName": "Spaghetti",
"providerFirstName": "Mom",
"iterationIsComplete": true,
"familyIntendedProviderCity": "Austin",
"familyIntendedProviderName": "Mom Spaghetti",
"familyIntendedProviderEmail": "",
"familyIntendedProviderState": "IL",
"familyIntendedProviderAddress": "1 Main St",
"familyIntendedProviderPhoneNumber": ""
},
{
"uuid": "b22dde9c-2264-48b6-bd34-de5e22fea0e5",
"providerType": "Care Program",
"providerLastName": "Stinson", …
```

[CCAP-932] storing providerResponseAgreeToCare at the provider level for multi provider

---

src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
src/test/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerServiceTest_MultipleProvider.java

[CCAP-975](https://codeforamerica.atlassian.net/browse/CCAP-975)
- When preparing main pdf, if the feature flag is on, it will take the first provider in the child care schedules and will look to see if there is a providerResponseSubmissionId. if there is, it will look for the provider submission with that uuid.
- If there is no matching provider submission, it will use the family intended response instead
- The same logic applies for multiple provider pdf
- Includes the coverage for the provider preparer service.
[CCAP-975]: https://codeforamerica.atlassian.net/browse/CCAP-975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-975] - map multiple provider responses to pdf

---

src/main/java/org/ilgcc/app/submission/conditions/DisplaySchedulesSameScreen.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java

CCAP-966
***
The intention is that the screen should not be displayed if there are two or more different schedules with the same provider. If the family report a schedule for the first provider, then use the schedules-same screen to specify that the schedule for the second child is the same as for the first child, they should also be presented with the schedules-same screen for a third child and so on until there are two different schedules for that provider.
***

[CCAP-966] Updated logic to match navigation intention for same-screen

---

src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailNoProviderTemplate.java
src/main/java/org/ilgcc/app/email/templates/FamilyConfirmationEmailTemplate.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/email/SendFamilyConfirmationEmailTest.java
src/test/java/org/ilgcc/app/email/SendFamilyConfirmationNoProviderEmailTest.java

[CCAP-1018](https://codeforamerica.atlassian.net/browse/CCAP-1018)
[CCAP-1020](https://codeforamerica.atlassian.net/browse/CCAP-1020)
- updates email copy and sends different version when there is a single provider and when there are multiple
_**CCAP-1018 : Emailing with providers**_
**When enable multiple providers flag is off**
**When enable multiple providers flag is on**
... and there are multiple providers
... and there is a single provider
_**CCAP-1020 : Emailing with no provider**_
**When enable multiple providers flag is off**
**When enable multiple providers flag is on**
[CCAP-1018]: https://codeforamerica.atlassian.net/browse/CCAP-1018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCAP-1020]: …

[CCAP-1018], [CCAP-1020] - send email when applying with only providers and no provider

---

src/main/java/org/ilgcc/app/data/TransactionRepository.java
src/main/java/org/ilgcc/app/data/TransmissionRepository.java

The timezone shifting was incorrect in these queries, causing submissions that were expired for 1 hour to be picked up in < 1 hour.
Here is a slightly modified version of the transaction query as proof of the issue.
```
SELECT id, submitted_at, short_code, TO_TIMESTAMP((s.input_data->>'providerApplicationResponseExpirationDate')::double precision)::timestamptz as expiration, (now() AT TIME ZONE 'UTC' AT TIME ZONE 'America/Chicago') as queryNow, (now() AT TIME ZONE 'UTC') as actualNow
FROM submissions s 
JOIN transactions t ON t.submission_id = s.id 
WHERE s.submitted_at IS NOT NULL 
AND ( 
s.input_data->>'providerResponseStatus' = 'ACTIVE' 
OR s.input_data->>'providerResponseStatus' IS NULL 
) 
AND s.input_data->>'providerApplicationResponseExpirationDate' IS NOT NULL 
AND …
```

[CCAP-755] Fixing timezone issue on expiration date in query

---

src/main/java/org/ilgcc/app/pdf/MultiProviderPDFService.java
src/main/java/org/ilgcc/app/pdf/ProviderSubmissionFieldPreparerService.java
src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
src/main/java/org/ilgcc/app/submission/conditions/MultiProviderIsEnabledAndHasMultipleProviders.java
src/main/java/org/ilgcc/app/submission/conditions/MultiProviderIsEnabledAndIsNotSingleProviderApplication.java
src/main/java/org/ilgcc/app/submission/filters/ProvidersWithChildcareSchedules.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/java/org/ilgcc/app/utils/SchedulePreparerUtility.java
src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java
src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
src/test/java/org/ilgcc/app/utils/SubmissionUtilitiesTest.java

CCAP-1097
This implements a change that will skip the `multi-provider` and `confirm-provider` screens in the `providerresponse` flow if: 
- The family application was only for a single provider when `ENABLE_MULTIPLE_PROVIDERS` is turned on
- The family application had multiple providers but only one was actually selected for all child care schedules
- The application uses the data structure prior to multi providers being enabled

[CCAP-1097] Skip multi-provider and confirm-provider screens for single provider applications

---

src/main/resources/messages.properties

https://codeforamerica.atlassian.net/browse/CCAP-1057
Update the copy for the version of the content that is shown to users on the submit-start screen if the time for the provider to respond has expired.

[CCAP-1057] : Update copy on the providerresponse/submit-start screen

---

src/main/java/org/ilgcc/app/pdf/NeedChildcareChildrenPreparer.java

CCAP-1148
Fixes an issue where child care schedules were not being mapped to the PDF when a family submission had multi-provider off but the provider submission had it on.

[CCAP-1148] Fix child care schedule PDF mappings

---

src/main/java/org/ilgcc/app/submission/actions/SetCurrentProviderForSingleProviderSubmission.java
src/main/java/org/ilgcc/app/submission/conditions/MultiProviderIsEnabledAndHasMultipleProviders.java
src/main/resources/flows-config.yaml
src/test/java/org/ilgcc/app/journeys/ProviderresponseMultiProviderFlowJourneyTest.java

CCAP-1191
Fixes the following issues:
**Scenario 1:**
1. Create a family application with 2 or more children
2. Indicate that not all children have a provider on the providers-all-ccap-children screen
3. In the schedules section, assign all children to one or more providers. i.e. do not add a schedule for any child with no provider
4. Respond on behalf of all the providers on the application
5. Transmission of the application to CCMS will fail
**Scenario 2:**
1. Create a family application with multiple children and providers
2. Respond on behalf of the provider but start on the https://localhost:8080/flow/providerresponse/submit-start screen
3. Add the confirmation code
4. The multiple-provider screen will skip

[CCAP-1191] Fix current provider ID bug

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java

https://codeforamerica.atlassian.net/browse/CCAP-1215
Provider user files need to follow the same pattern as family user files, and if pdf modification is enabled, we need to use a different method so we don't send the locked/encrypted files too. Pulled this out into a little helper method which could, theoretically, wind up in FFL at some point but not sure about that. Would rather fix the bug and contemplate that at some other point.
Currently in Staging, we see when a CCMS transaction for a submission + 2 files being uploaded:
There are 2 logging statements for each of the 2 files, so 4 total logging statements.
Here's what's in the database for the user_files for the family side:
... and then:
The Provider also uploaded 2 documents, we converted them (by removing the security …

[CCAP-1215] Provider docs need to filter out original files if PDF modification is enabled

---

src/main/java/org/ilgcc/app/RobotsController.java
src/test/java/org/ilgcc/app/RobotsControllerTest.java

CCAP-1209
The search console will not accept the sitemap without being provided a full canonical URL in the robots.txt for crawling. This PR fixes that issue by providing the full canonical URL in the production environments robots.txt file where its needed.
Adds one unit test each for prod and non prod environments. The unit tests set the active spring profile to 'production' and 'qa' to mimic prod and non prod results when calling `getRobotsTxt` in the RobotsController. The unit tests should be sufficient for local testing but ultimately this will need to be merged and released before CCAP-1209 can be completed by actually submitting the sitemap to the Google and Bing search consoles.
The above testing gives me confidence this should work in production but should it fail, we can create …

[CCAP-1209] Make sitemap discoverable with full URL in prod

---

src/main/java/org/ilgcc/app/email/ILGCCEmail.java
src/main/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedProviderConfirmationEmail.java
src/main/java/org/ilgcc/app/email/templates/FamilyApplicationTransmittedProviderConfirmationTemplate.java
src/main/java/org/ilgcc/app/inputs/Providerresponse.java
src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/main/resources/messages.properties
src/test/java/org/ilgcc/app/email/SendFamilyApplicationTransmittedProviderConfirmationTest.java

[CCAP-997](https://codeforamerica.atlassian.net/browse/CCAP-997)
- When an application has been transmitted, email the providers to let them know the application has been transmitted
- Adds Tests
Link to test scenarios: https://codeforamerica.atlassian.net/browse/CCAP-997?focusedCommentId=20251
Emails when Multiple providers
Emails when Single Provider
[CCAP-997]: https://codeforamerica.atlassian.net/browse/CCAP-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-997] - send email to provider when application is transmitted

---

src/main/java/org/ilgcc/app/data/ccms/CCMSApiClient.java

Removing a single extra space from a logging statement, mostly to test some hotfix stuff and needing a branch to do so.

Removing extra space from logging statement

---

src/main/java/org/ilgcc/app/utils/SubmissionUtilities.java

https://codeforamerica.atlassian.net/browse/CCAP-1249
We already set a provider that is not assigned to a schedule at all to INACTIVE [here in GenerateShortLinkAndStoreProviderApplicationStatus](https://github.com/codeforamerica/il-gcc-form-flow/blob/main/src/main/java/org/ilgcc/app/submission/actions/GenerateShortLinkAndStoreProviderApplicationStatus.java#L81). 
This change basically just means that, as each provider responds, we handle INACTIVE the same as RESPONDED. If all providers are RESPONDED _or_ INACTIVE, we just need to then mark the entire application as done vs leaving it open for responses because 1 or more providers are INACTIVE.
I'm not quite sure how to prove this works with the PR itself, but here's a json blob showing 2 RESPONDED and 1 INACTIVE:
And here's an email to …

[CCAP-1249] Provider with no schedule not treated properly in response flow

---

src/main/resources/messages.properties
src/main/resources/templates/faq.html
src/main/resources/templates/index.html

[CCAP-1243](https://codeforamerica.atlassian.net/browse/CCAP-1243)
- this assumes that cohort 2 is part of the pending sdas
- When enable additional sdas is off, we will still display county language
- 
- When enable additional sdas is on, we will not display county language
[CCAP-1243]: https://codeforamerica.atlassian.net/browse/CCAP-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CCAP-1243] - Keep counties language when enable new sda flag is off

---

src/main/resources/templates/gcc/activities-add-jobs.html
src/main/resources/templates/gcc/activities-partner-add-job.html
src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java
src/test/java/org/ilgcc/app/journeys/GccSingleProviderJourneyTest.java

🔗 Jira ticket
https://codeforamerica.atlassian.net/browse/CCAP-1197?
✍️ Description
Make remove links unambiguous for screen reader users on activities "add-jobs" screens
📷 Design reference
1)With NVDA enabled, Navigate to gcc/activities-add-jobs-list & gcc/activities-partner-add-jobs-list
2) Tab to the remove link for any listed job
3)Screen reader should announce 'Remove [Company Name]'.
For example “remove Code for America”.

[CCAP-1197] Make remove links unambiguous for screen reader users on activities "add-jobs" screens

---

src/main/resources/templates/providerresponse/registration-household-add-person.html
src/test/java/org/ilgcc/app/journeys/ProviderresponseProviderRegistrationJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-1201
The “remove” links on the providerresponse/registration-household-add-person screen now announces the first and last name of the person.

[CCAP-1201]- The “remove” links on the providerresponse/registration-household-add-person screen now announces the first and last name of the person.

---

src/main/resources/templates/gcc/providers-add.html
src/test/java/org/ilgcc/app/journeys/GccMultiProviderFlowJourneyTest.java

https://codeforamerica.atlassian.net/browse/CCAP-1199
Each “edit details” link should be announced by the screen reader with the name of the provider in the list.
Each “remove” link should be announced by the screen reader with the name of the provider in the list.
https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=18967-47776&t=2kWIOs4rKNIg5txD-4

[CCAP-1199] : Make remove and edit links unambiguous for screen reader users on gcc/providers-add screen

---

src/main/java/org/ilgcc/app/ProviderLinkController.java

Potential fix for [https://github.com/codeforamerica/il-gcc-form-flow/security/code-scanning/1004](https://github.com/codeforamerica/il-gcc-form-flow/security/code-scanning/1004)
To fix this vulnerability:
1. **Always use parameterized logging** with placeholders (`{}`) for user input, instead of string concatenation. This helps loggers treat the user input as a value (protecting against malformed formatting and making delimiters clearer).
2. **Clearly delimit the user input in log entry** (for example, surrounding with single quotes).
3. The existing `sanitize` method is already effective at removing control characters (such as newlines), but we will keep its use as a defense-in-depth measure.
4. Apply the same fix on any other log entries using the user input (for instance, the DEBUG …

Potential fix for code scanning alert no. 1004: Log Injection

---

src/main/java/org/ilgcc/app/submission/actions/ValidateBirthdate.java
src/test/java/org/ilgcc/app/submission/actions/ValidateBirthdateTest.java

CCAP-1263
Prevent `null` values from being passed into Birthdates.

[CCAP-1263] Update ValidateBirthdate to throw null value errors

---

src/main/java/org/ilgcc/app/submission/actions/PartnerSetJobWeeklyScheduleGroup.java
src/main/java/org/ilgcc/app/submission/actions/SetJobWeeklyScheduleGroup.java
src/main/java/org/ilgcc/app/submission/actions/SetSubflowWeeklyScheduleGroup.java
src/main/java/org/ilgcc/app/submission/actions/SetWeeklyScheduleGroup.java
src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/static/assets/css/custom.css
src/main/resources/templates/fragments/inputs/timeRange.html
src/main/resources/templates/fragments/inputs/timeSelect.html
src/test/java/org/ilgcc/app/submission/actions/SetClassWeeklyScheduleGroupTest.java

CCAP-1318, CCAP-1319
CCAP-1318 - For all places where we collect schedule data with hours/minutes/AM-PM inputs, the html id attributes need to be unique.
CCAP-1319 - Legend fields should be inside the fieldset tags instead of outside.
Tested using WebAim WAVE Accessibility plugin
**Fieldset / Legend Issues Before**
**Fieldset / Legend Issues After**
We go from 27 reported issues to 3 non-related / not actual issues. 
** Unique IDs**

[CCAP-1318, CCAP-1319] Fix fieldset and legend ordering and ensure unique IDs for fields

---

src/main/java/org/ilgcc/app/data/Transaction.java
src/main/java/org/ilgcc/app/data/TransactionRepositoryService.java
src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/app/utils/enums/TransactionType.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/main/resources/db/migration/V2025.09.24.13.32.46__Add_transaction_type_column_to_transactions_table.sql
src/test/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJobTest.java
src/test/java/org/ilgcc/jobs/DailyNewApplicationsProviderEmailRecurringJobTest.java

CCAP-1289
Adds a migration to add TransactionType to the Transaction DB table.
Updates transaction related code to set transaction type to APPLICATION on new transactions created by sendToCCMS method.

[CCAP-1289] Add TransactionType to Transaction

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/app/data/ccms/TransactionFile.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java
src/test/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJobTest.java

[Fixes an issue were UserFileTransaction records were failing to be created here.
](https://codeforamerica.sentry.io/issues/6903738840/?alert_rule_id=15385157&alert_type=issue&notification_uuid=4c95e0a5-31ea-4150-968e-a4cec6d80e3d&project=4506815935545344&referrer=slack)
The issue is because we need UserFile IDs to be created for each file we sent to CCMS, which now includes the application PDF. This means we need to now create a user file for the application PDFs when they are generated, upload them to S3 for storage in case we need to resubmit them later, and then save the corresponding transaction and userfile id to the UserFileTransaction table. 
This change means that we need to throw if uploading to S3 fails since this step is now important for resubmission. Additionally, if the …

[CCAP-1376] Fixes an issue with UserFileTransaction saving - Merge after 1289

---

src/main/resources/templates/fragments/inputs/overrides/fileUploader.html

🔗 Jira ticket
(https://codeforamerica.atlassian.net/browse/CCAP-193?
✍️ `Description`
1) Fixed JAWS screen reader not announcing uploaded file names while other screen readers like VoiceOver worked correctly.
2) The root cause was accessibility barriers preventing JAWS from reading filename content in the file upload component.
3) Implemented targeted accessibility improvements to ensure JAWS can properly access and announce uploaded file names.
4) Testing confirms JAWS now properly announces file names when navigating through uploaded files with no regression in other screen readers.

[CCAP-193]-Fix JAWS Screen Reader Announcement for Uploaded File Names

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/app/exception/FatalJobrunrErrorDoNotRetryException.java
src/main/java/org/ilgcc/app/exception/S3ObjectNotFoundException.java
src/main/java/org/ilgcc/app/exception/S3ObjectNotScannedException.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java
src/test/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJobTest.java

https://codeforamerica.atlassian.net/browse/CCAP-1437
When we know the job will never succeed, we don't need to retry N times. This is a generic exception on top of the Jobrunr exception that will kill the job immediately.
Logs will now look like this:
And then within Jobrunr, there will be 1 failure and it'll look like this:
This means we will immediately get the alert for the retry failures, and then we will know the submission and jobrunr job to investigate.

[CCAP-1437] Reduce noise and kill job when multiple retries will never ever matter

---

src/main/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadService.java
src/main/java/org/ilgcc/app/data/ccms/TransactionFile.java
src/main/java/org/ilgcc/app/utils/enums/CCMSEndpoints.java
src/main/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJob.java
src/test/java/org/ilgcc/app/data/ccms/CCMSTransactionPayloadServiceTest.java
src/test/java/org/ilgcc/jobs/CCMSSubmissionPayloadTransactionJobTest.java

CCAP-1287
Update the ILGCC application submission workflow so that when the ENABLE_CCMS_APPLICATION_V2 feature flag is enabled, application payloads are routed through the new v2/appSubmission API endpoint.
**V2 Api returns correct files after sending submission to V2 Endpoint**
**CCMS Correct creates entries when v2 endpoint is hit**
**User File Transaction shows correct rows for PDF and 2 additional provider PDFs**

[CCAP-1287] Enable sending transactions to V2 CCMS endpoint
